### PR TITLE
WELD-1941 Fix default bean names for managed and session beans

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of b9854d41b9bf602e206c3122c9c63b5a85aa2df8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 754 is now running using a merge of b9854d41b9bf602e206c3122c9c63b5a85aa2df8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/754

**Comment by weld-tester** [comment]
Build 754 outcome was SUCCESS using a merge of b9854d41b9bf602e206c3122c9c63b5a85aa2df8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/754
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/754

**Comment by weld-tester** [comment]
Build 754 outcome was SUCCESS using a merge of b9854d41b9bf602e206c3122c9c63b5a85aa2df8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/754
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/754

**Comment by weld-tester** [comment]
Build 754 outcome was SUCCESS using a merge of b9854d41b9bf602e206c3122c9c63b5a85aa2df8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/754
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/754

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
