### PR TITLE
WELD-2302 Wro4j maven plugin does not work with JDK 9

### PR DESCRIPTION
**Pull request by antoinesd**
upgrade plugin and Mockito dependency to have a Mockito version supporting Java 9

### CODE REVIEW

**Comment by mkouba** [comment]
ok to test

**Comment by mkouba** [comment]
add to whitelist

**Comment by manovotn** [comment]
Looks OK, though we cannot be sure this will make it into wro plugin itself (they are using prehistoric `2.0.42-beta` there). Therefore, we cannot be sure this won't effect the plugin's functionality in some weird way.
Although as far as tests are concerned, it looks alright. 

@antoinesd please create similar PR for 2.4 branch

**Comment by antoinesd** [comment]
Well @manovotn, Mockito is used only in 2 methods in the code so it should be easy to test a possible issue.
Will backport to 2.4 as well.

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
