### PR TITLE
WELD-1877 Ignore WEB-INF/classes/META-INF/beans.xml properly if WEB-INF/beans.xml exists

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 227f52da4294051b64ee620831864c7ae17279b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 531 is now running using a merge of 227f52da4294051b64ee620831864c7ae17279b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/531

**Comment by weld-tester** [comment]
Build 531 outcome was SUCCESS using a merge of 227f52da4294051b64ee620831864c7ae17279b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/531
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/531

**Comment by weld-tester** [comment]
Build 531 outcome was SUCCESS using a merge of 227f52da4294051b64ee620831864c7ae17279b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/531
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/531

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
