### PR TITLE
CDI 2.0-EDR1, WELD-1977

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 902 is now running using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/902

**Comment by weld-tester** [comment]
Build 902 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/902
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/902

**Comment by weld-tester** [comment]
Build 902 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/902
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/902

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 903 is now running using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/903

**Comment by weld-tester** [comment]
Build 903 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/903
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/903

**Comment by weld-tester** [comment]
Build 903 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/903
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/903

**Comment by weld-tester** [comment]
Build 903 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/903
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/903

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 906 is now running using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/906

**Comment by weld-tester** [comment]
Build 906 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/906
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/906

**Comment by mkouba** [comment]
Note that I have reverted https://github.com/weld/api/pull/28 because we need to upgrade CDI API to 2.0-EDR1 and release weld-api 3.0.Alpha12 first.

**Comment by weld-tester** [comment]
Build 906 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/906
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/906

**Comment by weld-tester** [comment]
Triggering build using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 936 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/936
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/936

**Comment by weld-tester** [comment]
Build 936 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/936
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/936

**Comment by weld-tester** [comment]
Build 936 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/936
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/936

**Comment by weld-tester** [comment]
Build 936 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/936
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/936

**Comment by weld-tester** [comment]
Build 936 outcome was FAILURE using a merge of 1812f30c4f815b61d574915a46f8a8fb07fb54c6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/936
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/936

**Comment by jharting** [comment]
Superseded by https://github.com/weld/core/pull/1083

**Pull request closed without merging**
