### PR TITLE
WELD-2480: Include JS dependencies licenses in weld-probe-core.jar

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by manovotn** [comment]
Shouldn't we maybe review and update all those dependencies while at it?

**Comment by mkouba** [comment]
AFAIR we cannot easily upgrade Ember.js and its deps because versions 2.0+ require some additional migration work as it is not backward compatible. So I think we could create a new issue but since probe is a dev phase tool it should be probably low priority.

**Comment by manovotn** [comment]
If you want to, create that separate JIRA for dep update.

**Comment by manovotn** [comment]
retest this please

**Pull request merged**
