### PR TITLE
WELD-1860

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 529 is now running using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/529

**Comment by weld-tester** [comment]
Build 529 outcome was FAILURE using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/529
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/529

**Comment by weld-tester** [comment]
Build 529 outcome was FAILURE using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/529
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/529

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 530 is now running using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/530

**Comment by weld-tester** [comment]
Build 530 outcome was SUCCESS using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/530
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/530

**Comment by weld-tester** [comment]
Build 530 outcome was SUCCESS using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/530
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/530

**Comment by weld-tester** [comment]
Build 530 outcome was SUCCESS using a merge of a9615100bd8381efbba9b3e342de24da47ad5d02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/530
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/530

**Comment by weld-tester** [comment]
Triggering build using a merge of 8ee7f6e3147d59a66f711406d485a18d3f51d881 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 536 is now running using a merge of 8ee7f6e3147d59a66f711406d485a18d3f51d881 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/536

**Comment by weld-tester** [comment]
Build 536 outcome was SUCCESS using a merge of 8ee7f6e3147d59a66f711406d485a18d3f51d881 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/536
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/536

**Comment by weld-tester** [comment]
Triggering build using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 537 is now running using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/537

**Comment by weld-tester** [comment]
Build 537 outcome was SUCCESS using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/537
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/537

**Comment by weld-tester** [comment]
Build 537 outcome was SUCCESS using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/537
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/537

**Comment by weld-tester** [comment]
Build 537 outcome was SUCCESS using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/537
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/537

**Comment by weld-tester** [comment]
Build 537 outcome was SUCCESS using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/537
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/537

**Comment by weld-tester** [comment]
Build 537 outcome was SUCCESS using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/537
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/537

**Comment by weld-tester** [comment]
Build 537 outcome was SUCCESS using a merge of 3d2d97092722bd1ac1348368a3789e0b2813ca27 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/537
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/537

**Pull request closed without merging**
