### PR TITLE
WELD-1966 Update Guava to 18.0

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 46593d4f9e8c8c6c43511d7893adddcfb462d06c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 826 is now running using a merge of 46593d4f9e8c8c6c43511d7893adddcfb462d06c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/826

**Comment by weld-tester** [comment]
Build 826 outcome was SUCCESS using a merge of 46593d4f9e8c8c6c43511d7893adddcfb462d06c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/826
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/826

**Comment by weld-tester** [comment]
Build 826 outcome was SUCCESS using a merge of 46593d4f9e8c8c6c43511d7893adddcfb462d06c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/826
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/826

**Comment by weld-tester** [comment]
Build 826 outcome was SUCCESS using a merge of 46593d4f9e8c8c6c43511d7893adddcfb462d06c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/826
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/826

**Comment by mkouba** [comment]
@davewinters it's included - see also https://github.com/weld/core/blob/2.3/pom.xml#L47 and https://github.com/weld/core/blob/2.3/bundles/osgi/pom.xml#L93

**Pull request closed without merging**
