### PR TITLE
Probe client - refactoring and cleanup

### PR DESCRIPTION
**Pull request by mkouba**
- get rid of global variables so that the client is more testable
- add helper to render a tooltip-like icon
- distinguish probe components (WELD-1886)
- further cleanup

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of dc54ca5427781e188216c774f3a0d0fd37039188 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 595 outcome was FAILURE using a merge of dc54ca5427781e188216c774f3a0d0fd37039188 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/595
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/595

**Comment by weld-tester** [comment]
Triggering build using a merge of cb02b8fa9f555ff436d4f7fbdf38f7143517fdb8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 596 is now running using a merge of cb02b8fa9f555ff436d4f7fbdf38f7143517fdb8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/596

**Comment by weld-tester** [comment]
Build 596 outcome was SUCCESS using a merge of cb02b8fa9f555ff436d4f7fbdf38f7143517fdb8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/596
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/596

**Comment by weld-tester** [comment]
Build 596 outcome was SUCCESS using a merge of cb02b8fa9f555ff436d4f7fbdf38f7143517fdb8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/596
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/596

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
