### PR TITLE
WELD-1945 Improve validation of lifecycle callback interceptor bindings

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 2620c54c32e0466893615e974dcb6a6aab4d78df on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 883 is now running using a merge of 2620c54c32e0466893615e974dcb6a6aab4d78df on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/883

**Comment by weld-tester** [comment]
Build 883 outcome was FAILURE using a merge of 2620c54c32e0466893615e974dcb6a6aab4d78df on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/883
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/883

**Comment by weld-tester** [comment]
Triggering build using a merge of 1390bf58fbe4e7dedeb216a2c69a4f5264bc21de on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 884 is now running using a merge of 1390bf58fbe4e7dedeb216a2c69a4f5264bc21de on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/884

**Comment by weld-tester** [comment]
Build 884 outcome was SUCCESS using a merge of 1390bf58fbe4e7dedeb216a2c69a4f5264bc21de on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/884
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/884

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 1390bf58fbe4e7dedeb216a2c69a4f5264bc21de on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 885 is now running using a merge of 1390bf58fbe4e7dedeb216a2c69a4f5264bc21de on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/885

**Comment by weld-tester** [comment]
Build 885 outcome was SUCCESS using a merge of 1390bf58fbe4e7dedeb216a2c69a4f5264bc21de on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/885
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/885

**Comment by weld-tester** [comment]
Build 885 outcome was SUCCESS using a merge of 1390bf58fbe4e7dedeb216a2c69a4f5264bc21de on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/885
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/885

**Pull request closed without merging**
