### PR TITLE
WELD-1841 Examples - remove examples/lib

### PR DESCRIPTION
**Pull request by mkouba**
- also add se/groovy-numberguess as a mvn module and upgrade groovy bits

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of ecabd0cb1e7ab6dbb2365e32f5f31f6dc1ea071e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 428 is now running using a merge of ecabd0cb1e7ab6dbb2365e32f5f31f6dc1ea071e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/428

**Comment by weld-tester** [comment]
Build 428 outcome was SUCCESS using a merge of ecabd0cb1e7ab6dbb2365e32f5f31f6dc1ea071e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/428
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/428

**Comment by weld-tester** [comment]
Triggering build using a merge of 080e9dacbdcfd2f088dc19ab399809e495128c73 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 430 is now running using a merge of 080e9dacbdcfd2f088dc19ab399809e495128c73 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/430

**Comment by weld-tester** [comment]
Build 430 outcome was SUCCESS using a merge of 080e9dacbdcfd2f088dc19ab399809e495128c73 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/430
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/430

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
