### PR TITLE
WELD-1904 Process BootstrapConfiguration correctly

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of b91f720364112f55743816d85929fc81b1bb5f5c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 598 is now running using a merge of b91f720364112f55743816d85929fc81b1bb5f5c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/598

**Comment by weld-tester** [comment]
Build 598 outcome was SUCCESS using a merge of b91f720364112f55743816d85929fc81b1bb5f5c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/598
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/598

**Comment by weld-tester** [comment]
Build 598 outcome was SUCCESS using a merge of b91f720364112f55743816d85929fc81b1bb5f5c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/598
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/598

**Comment by weld-tester** [comment]
Build 598 outcome was SUCCESS using a merge of b91f720364112f55743816d85929fc81b1bb5f5c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/598
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/598

**Comment by weld-tester** [comment]
Build 598 outcome was SUCCESS using a merge of b91f720364112f55743816d85929fc81b1bb5f5c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/598
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/598

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
