### PR TITLE
Backport of WELD-1478 to EAP 6. Possible memory leak in HttpConversationContextImpl.

### PR DESCRIPTION
**Pull request by rpelisse**
[BZ1224358](https://bugzilla.redhat.com/show_bug.cgi?id=1224358) - Backport of WELD-1478 possible memory leak in HttpConversationContextImpl to 1.1.x for EAP.

### CODE REVIEW

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
https://github.com/weld/core/commit/d93820f5174274480973a7831bf33c456e389696 is tightly related. We should backport this commit as well.

**Comment by rpelisse** [comment]
No prob', I'll do the backport too. Should I group them into one PR ? (thus closing this one ?)

**Comment by jharting** [comment]
Yes, one PR is OK. You can just add the additional commit to the branch and this PR will be updated.

**Comment by rpelisse** [comment]
OK, I've also backported the [other commit](https://github.com/rpelisse/weld-core/commit/5087d7dcb1f5f3ed50b9da7778b78833b90412ce), let me know if it all looks good to you.

**Comment by jharting** [comment]
There seems to be a lot of undesirable formatting changes in the PR.

**Comment by rpelisse** [comment]
Grrrr.... I had to use Eclipse Format feature to appease the Checkstyle plugin, and it seems, it has does way more formatting than I wanted.

Let me try to fix that...

**Comment by rpelisse** [comment]
Superseed by [PR997](https://github.com/weld/core/pull/997).

**Pull request closed without merging**
