### PR TITLE
WELD-1926 Use more specific payload for container event fired during shutdown

### PR DESCRIPTION
**Pull request by mkouba**
- the payload allows to inspect the container id as well

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 80da9ba2d722064bd180b98a6f4beed5159a8ed7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 700 is now running using a merge of 80da9ba2d722064bd180b98a6f4beed5159a8ed7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/700

**Comment by weld-tester** [comment]
Build 700 outcome was SUCCESS using a merge of 80da9ba2d722064bd180b98a6f4beed5159a8ed7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/700
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/700

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
