### PR TITLE
WELD-1985, WELD-1986, WELD-1989 (Probe)

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d548a786da4905b0029b54c7f34ee2339f0f89e1 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 909 is now running using a merge of d548a786da4905b0029b54c7f34ee2339f0f89e1 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/909

**Comment by weld-tester** [comment]
Build 909 outcome was SUCCESS using a merge of d548a786da4905b0029b54c7f34ee2339f0f89e1 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/909
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/909

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
