### PR TITLE
WFLY-4572 Exclude slf4j-api:1.7.7.jbossorg-1 not available in central

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 83333b8579328127041cc32cab73a86f19251524 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 730 is now running using a merge of 83333b8579328127041cc32cab73a86f19251524 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/730

**Comment by weld-tester** [comment]
Build 730 outcome was SUCCESS using a merge of 83333b8579328127041cc32cab73a86f19251524 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/730
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/730

**Comment by mkouba** [comment]
It seems we can exclude the problematic artifact safely.

**Comment by mkouba** [comment]
I will try to replace the `wildfly-arquillian-common` dependency with `wildfly-controller-client` and `jboss-dmr`.

**Comment by weld-tester** [comment]
Build 730 outcome was SUCCESS using a merge of 83333b8579328127041cc32cab73a86f19251524 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/730
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/730

**Comment by mkouba** [comment]
It would be possible to replace `wildfly-arquillian-common` completely (and use reflection in `org.jboss.weld.tck.wildfly8.WildFly8Extension` to override the `org.jboss.as.arquillian.container.ExceptionTransformer`) but in the long term, it would be probably better to add an exclude temporarily.

**Comment by weld-tester** [comment]
Triggering build using a merge of adce52f090c9eee1ddb58d6aa2cc622bc71ab072 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 743 is now running using a merge of adce52f090c9eee1ddb58d6aa2cc622bc71ab072 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/743

**Comment by weld-tester** [comment]
Build 743 outcome was SUCCESS using a merge of adce52f090c9eee1ddb58d6aa2cc622bc71ab072 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/743
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/743

**Comment by weld-tester** [comment]
Build 743 outcome was SUCCESS using a merge of adce52f090c9eee1ddb58d6aa2cc622bc71ab072 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/743
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/743

**Comment by weld-tester** [comment]
Build 743 outcome was SUCCESS using a merge of adce52f090c9eee1ddb58d6aa2cc622bc71ab072 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/743
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/743

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
