### PR TITLE
WELD-1943, WELD-1944 BeanBuilder improvements

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 20a2516b8b9da6c2da7a83f3bd9ce60f08c80e9b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 751 outcome was FAILURE using a merge of 20a2516b8b9da6c2da7a83f3bd9ce60f08c80e9b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/751
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/751

**Comment by weld-tester** [comment]
Build 751 outcome was FAILURE using a merge of 20a2516b8b9da6c2da7a83f3bd9ce60f08c80e9b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/751
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/751

**Comment by weld-tester** [comment]
Build 751 outcome was FAILURE using a merge of 20a2516b8b9da6c2da7a83f3bd9ce60f08c80e9b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/751
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/751

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 4caabee752f8dd9fa90ffa9a45c837b20a3aa897 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 762 outcome was FAILURE using a merge of 4caabee752f8dd9fa90ffa9a45c837b20a3aa897 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/762
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/762

**Comment by weld-tester** [comment]
Build 762 outcome was FAILURE using a merge of 4caabee752f8dd9fa90ffa9a45c837b20a3aa897 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/762
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/762

**Comment by weld-tester** [comment]
Build 762 outcome was FAILURE using a merge of 4caabee752f8dd9fa90ffa9a45c837b20a3aa897 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/762
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/762

**Comment by weld-tester** [comment]
Triggering build using a merge of 670fa585012f458dda95237c337700bfdf8a6f6f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 765 is now running using a merge of 670fa585012f458dda95237c337700bfdf8a6f6f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/765

**Comment by weld-tester** [comment]
Build 765 outcome was SUCCESS using a merge of 670fa585012f458dda95237c337700bfdf8a6f6f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/765
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/765

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
