### PR TITLE
WELD-1871 Next part

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of df52eccf65907716f06b5d532db630fd16d508f6 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 935 is now running using a merge of df52eccf65907716f06b5d532db630fd16d508f6 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/935

**Comment by weld-tester** [comment]
Build 935 outcome was SUCCESS using a merge of df52eccf65907716f06b5d532db630fd16d508f6 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/935
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/935

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
