### PR TITLE
WELD-1977

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 895 outcome was FAILURE using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/895
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/895

**Comment by weld-tester** [comment]
Build 895 outcome was FAILURE using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/895
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/895

**Comment by weld-tester** [comment]
Build 895 outcome was FAILURE using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/895
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/895

**Comment by weld-tester** [comment]
Build 895 outcome was FAILURE using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/895
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/895

**Comment by weld-tester** [comment]
Build 895 outcome was FAILURE using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/895
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/895

**Comment by weld-tester** [comment]
Build 895 outcome was FAILURE using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/895
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/895

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 901 outcome was FAILURE using a merge of f4e9926a032e537eb47485aa22e1769db6f03347 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/901
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/901

**Pull request closed without merging**
