### PR TITLE
WELD-2269 implement BeforeDestroyed. Replace Initialized/Destroyed li…

### PR DESCRIPTION
**Pull request by manovotn**
…terals by those from CDI API.

Depends on - https://github.com/arquillian/arquillian-container-weld/pull/37
Some tests will currently fail because we use Weld embedded container which in turn uses our Literal impl.

### CODE REVIEW

**Comment by mkouba** [comment]
Pls rebase and squash all commits (or at least add Weld issue to the last commit message) and commit details could be in a list - see also https://github.com/weld/core/commit/f9f8dd33d25027e7a3ad3895633fc919df4869a4. Thanks! ;-)

**Comment by manovotn** [comment]
@mkouba done

**Comment by manovotn** [comment]
Fixed compilation problem (this commit removed our Literal impl and merge of WELD-2267 depended on it) and rebased. Let's see if Jenkins likes it now.

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
