### PR TITLE
reliable way of checking whether Weld already runs or not

### PR DESCRIPTION
**Pull request by otaviojava**
reliable way of checking whether Weld already runs or not

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d9caca4d19ec94c1862b71e98ad0937307cd0407 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 407 is now running using a merge of d9caca4d19ec94c1862b71e98ad0937307cd0407 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/407

**Comment by weld-tester** [comment]
Build 407 outcome was FAILURE using a merge of d9caca4d19ec94c1862b71e98ad0937307cd0407 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/407
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/407

**Comment by weld-tester** [comment]
Build 407 outcome was FAILURE using a merge of d9caca4d19ec94c1862b71e98ad0937307cd0407 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/407
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/407

**Comment by weld-tester** [comment]
Build 407 outcome was FAILURE using a merge of d9caca4d19ec94c1862b71e98ad0937307cd0407 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/407
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/407

**Comment by gastaldi** [comment]
:+1:

**Comment by gastaldi** [comment]
Why two booleans? I think a single boolean should be enough (isStarted())

**Comment by gastaldi** [comment]
Perhaps ````isInitialized()```` makes more sense, given that the method name is ````intialize()````

**Comment by mkouba** [comment]
Note that in 3.x the Weld SE API evolved: https://github.com/weld/core/pull/920

`WeldContainer.isRunning()`:
https://github.com/weld/core/blob/master/environments/se/core/src/main/java/org/jboss/weld/environment/se/WeldContainer.java#L248

Maybe we will backport this into 2.2.

**Comment by gastaldi** [comment]
:+1:

**Comment by otaviojava** [comment]
@gastaldi you are right, there is not reason to use two booleans.
@mkouba I followed the same name now.

**Comment by weld-tester** [comment]
Triggering build using a merge of bc48281a8b5bb4a31259842dd611dde5a0b0cf4a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 716 outcome was FAILURE using a merge of bc48281a8b5bb4a31259842dd611dde5a0b0cf4a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/716
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/716

**Comment by weld-tester** [comment]
Triggering build using a merge of 8037c7d6848a2f11423dda4a2e550c38af59304f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 717 is now running using a merge of 8037c7d6848a2f11423dda4a2e550c38af59304f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/717

**Comment by weld-tester** [comment]
Build 717 outcome was SUCCESS using a merge of 8037c7d6848a2f11423dda4a2e550c38af59304f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/717
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/717

**Comment by weld-tester** [comment]
Build 717 outcome was SUCCESS using a merge of 8037c7d6848a2f11423dda4a2e550c38af59304f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/717
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/717

**Comment by weld-tester** [comment]
Build 717 outcome was SUCCESS using a merge of 8037c7d6848a2f11423dda4a2e550c38af59304f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/717
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/717

**Comment by jharting** [comment]
Out of date

**Pull request closed without merging**
