### PR TITLE
WELD-1843 Weld Servlet - bda id should be consistent between multiple

### PR DESCRIPTION
**Pull request by mkouba**
occurrences of the deployment

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 540 is now running using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/540

**Comment by weld-tester** [comment]
Build 540 outcome was SUCCESS using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/540
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/540

**Comment by weld-tester** [comment]
Build 540 outcome was SUCCESS using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/540
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/540

**Comment by weld-tester** [comment]
Build 540 outcome was SUCCESS using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/540
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/540

**Comment by weld-tester** [comment]
Build 540 outcome was SUCCESS using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/540
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/540

**Comment by weld-tester** [comment]
Build 540 outcome was SUCCESS using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/540
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/540

**Comment by jharting** [comment]
Merged, thanks!

**Comment by weld-tester** [comment]
Build 540 outcome was SUCCESS using a merge of e520940537941bccf1762105d0542885db182f8a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/540
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/540

**Pull request closed without merging**
