### PR TITLE
WELD-1972 Interceptor proxy dependencies not exported

### PR DESCRIPTION
**Pull request by hwellmann**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 848 outcome was FAILURE using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/848
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/848

**Comment by weld-tester** [comment]
Build 848 outcome was FAILURE using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/848
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/848

**Comment by weld-tester** [comment]
Build 848 outcome was FAILURE using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/848
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/848

**Comment by weld-tester** [comment]
Build 848 outcome was FAILURE using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/848
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/848

**Comment by weld-tester** [comment]
Build 848 outcome was FAILURE using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/848
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/848

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 852 is now running using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/852

**Comment by weld-tester** [comment]
Build 852 outcome was SUCCESS using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/852
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/852

**Comment by weld-tester** [comment]
Build 852 outcome was SUCCESS using a merge of 0b4fc5cdb2e982c95223564d9134e00ec2f273eb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/852
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/852

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
