### PR TITLE
WELD-1888, WELD-1891 - bean identifier index optimization

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 943c02a2ab2609a9cbdf100f51dc4cc035a0c237 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 567 outcome was FAILURE using a merge of 943c02a2ab2609a9cbdf100f51dc4cc035a0c237 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/567
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/567

**Comment by weld-tester** [comment]
Build 567 outcome was FAILURE using a merge of 943c02a2ab2609a9cbdf100f51dc4cc035a0c237 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/567
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/567

**Comment by weld-tester** [comment]
Build 567 outcome was FAILURE using a merge of 943c02a2ab2609a9cbdf100f51dc4cc035a0c237 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/567
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/567

**Comment by mkouba** [comment]
There's one forgotten diamond in BeanIdentifierIndexTest...

**Comment by weld-tester** [comment]
Build 567 outcome was FAILURE using a merge of 943c02a2ab2609a9cbdf100f51dc4cc035a0c237 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/567
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/567

**Comment by weld-tester** [comment]
Triggering build using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 570 is now running using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/570

**Comment by weld-tester** [comment]
Build 570 outcome was SUCCESS using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/570
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/570

**Comment by weld-tester** [comment]
Build 570 outcome was SUCCESS using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/570
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/570

**Comment by weld-tester** [comment]
Build 570 outcome was SUCCESS using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/570
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/570

**Comment by weld-tester** [comment]
Build 570 outcome was SUCCESS using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/570
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/570

**Comment by weld-tester** [comment]
Build 570 outcome was SUCCESS using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/570
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/570

**Comment by weld-tester** [comment]
Build 570 outcome was SUCCESS using a merge of 70249a2b7befc8505f854fa1e9615c5653c3a46c on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/570
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/570

**Comment by jharting** [comment]
Looks good to me. Go ahead with disabling this optimization by default for weld-servlet.

**Comment by weld-tester** [comment]
Triggering build using a merge of c36a82bf8a0b9fe0e7cd2c4998a67cee36d61f9a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 580 is now running using a merge of c36a82bf8a0b9fe0e7cd2c4998a67cee36d61f9a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/580

**Comment by weld-tester** [comment]
Build 580 outcome was SUCCESS using a merge of c36a82bf8a0b9fe0e7cd2c4998a67cee36d61f9a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/580
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/580

**Comment by weld-tester** [comment]
Build 580 outcome was SUCCESS using a merge of c36a82bf8a0b9fe0e7cd2c4998a67cee36d61f9a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/580
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/580

**Comment by weld-tester** [comment]
Build 580 outcome was SUCCESS using a merge of c36a82bf8a0b9fe0e7cd2c4998a67cee36d61f9a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/580
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/580

**Comment by weld-tester** [comment]
Build 580 outcome was SUCCESS using a merge of c36a82bf8a0b9fe0e7cd2c4998a67cee36d61f9a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/580
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/580

**Comment by weld-tester** [comment]
Build 580 outcome was SUCCESS using a merge of c36a82bf8a0b9fe0e7cd2c4998a67cee36d61f9a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/580
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/580

**Comment by jharting** [comment]
The docs should reflect that this optimization is disabled by default in weld-servlet

**Comment by weld-tester** [comment]
Triggering build using a merge of 435e483dd014be03999ab9bc23bc8e634cd85318 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 591 is now running using a merge of 435e483dd014be03999ab9bc23bc8e634cd85318 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/591

**Comment by weld-tester** [comment]
Build 591 outcome was SUCCESS using a merge of 435e483dd014be03999ab9bc23bc8e634cd85318 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/591
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/591

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
