### PR TITLE
WELD-1997 Expose Probe JSON data via JMX

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by mkouba** [comment]
We will need to add `javax.api` dependency to the WildFly `org.jboss.weld.probe` module.

**Comment by jharting** [comment]
I am wondering whether this should be enabled by default? (as long as development mode is enabled)

**Comment by mkouba** [comment]
Oops, I've forgotten to update the documentation.

**Comment by mkouba** [comment]
retest this please

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
