### PR TITLE
[2.2] WELD-1791 Revisit configuration

### PR DESCRIPTION
**Pull request by mkouba**
- introduce WeldConfiguration per-deployment service
- supported configuration keys can be found in ConfigurationKey enum

NOTE: This pull request depends on https://github.com/weld/api/pull/16 and the build will fail until it's merged.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 4713a4d73d1af8583253231c6f9e16cdac86cced on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 391 outcome was FAILURE using a merge of 4713a4d73d1af8583253231c6f9e16cdac86cced on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/391
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/391

**Comment by weld-tester** [comment]
Triggering build using a merge of 4713a4d73d1af8583253231c6f9e16cdac86cced on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 423 outcome was FAILURE using a merge of 4713a4d73d1af8583253231c6f9e16cdac86cced on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/423
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/423

**Comment by jharting** [comment]
Superseded by https://github.com/weld/core/pull/891

**Pull request closed without merging**
