### PR TITLE
WELD-1899 OSGi bundle - ensure GlassFish 4 compatibility

### PR DESCRIPTION
**Pull request by mkouba**
- see also WELD-1712

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 5e0975208004f5eae718a783c95720d5ad188cac on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 593 is now running using a merge of 5e0975208004f5eae718a783c95720d5ad188cac on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/593

**Comment by weld-tester** [comment]
Build 593 outcome was SUCCESS using a merge of 5e0975208004f5eae718a783c95720d5ad188cac on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/593
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/593

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
