### PR TITLE
WELD-1968 Mark generated proxy classes and subclasses as synthetic

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 832 is now running using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by weld-tester** [comment]
Build 832 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by weld-tester** [comment]
Build 832 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by weld-tester** [comment]
Build 832 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by weld-tester** [comment]
Build 832 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by weld-tester** [comment]
Build 832 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by weld-tester** [comment]
Build 832 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by weld-tester** [comment]
Build 832 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/832
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/832

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 841 is now running using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/841

**Comment by weld-tester** [comment]
Build 841 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/841
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/841

**Comment by weld-tester** [comment]
Build 841 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/841
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/841

**Comment by weld-tester** [comment]
Build 841 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/841
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/841

**Comment by weld-tester** [comment]
Build 841 outcome was FAILURE using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/841
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/841

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 854 is now running using a merge of 0ffd0086948b423bbdf0b4b20a3a1d8d274f3c8a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/854

**Comment by weld-tester** [comment]
Triggering build using a merge of 89f86fbcd5070ac65d90915a5df1b2e059621755 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 855 is now running using a merge of 89f86fbcd5070ac65d90915a5df1b2e059621755 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/855

**Comment by weld-tester** [comment]
Build 855 outcome was SUCCESS using a merge of 89f86fbcd5070ac65d90915a5df1b2e059621755 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/855
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/855

**Comment by weld-tester** [comment]
Build 855 outcome was SUCCESS using a merge of 89f86fbcd5070ac65d90915a5df1b2e059621755 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/855
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/855

**Comment by weld-tester** [comment]
Build 855 outcome was SUCCESS using a merge of 89f86fbcd5070ac65d90915a5df1b2e059621755 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/855
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/855

**Comment by weld-tester** [comment]
Build 855 outcome was SUCCESS using a merge of 89f86fbcd5070ac65d90915a5df1b2e059621755 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/855
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/855

**Pull request closed without merging**
