### PR TITLE
WELD-1959 Fix Jetty container detection

### PR DESCRIPTION
**Pull request by mkouba**
- also upgrade test versions of Tomcat and Jetty

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 3386ee0f2e87f3f305897400b94cf6dffcee665e on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 783 is now running using a merge of 3386ee0f2e87f3f305897400b94cf6dffcee665e on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/783

**Comment by weld-tester** [comment]
Build 783 outcome was SUCCESS using a merge of 3386ee0f2e87f3f305897400b94cf6dffcee665e on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/783
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/783

**Comment by weld-tester** [comment]
Build 783 outcome was SUCCESS using a merge of 3386ee0f2e87f3f305897400b94cf6dffcee665e on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/783
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/783

**Comment by weld-tester** [comment]
Build 783 outcome was SUCCESS using a merge of 3386ee0f2e87f3f305897400b94cf6dffcee665e on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/783
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/783

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
