### PR TITLE
WELD-1871 Next part

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 429892ebb08890152f938e4f3c3a3706f0a5da5d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 934 is now running using a merge of 429892ebb08890152f938e4f3c3a3706f0a5da5d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/934

**Comment by weld-tester** [comment]
Build 934 outcome was SUCCESS using a merge of 429892ebb08890152f938e4f3c3a3706f0a5da5d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/934
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/934

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
