### PR TITLE
remove support for @New beans

### PR DESCRIPTION
**Pull request by Ladicek**
This commit is WORK IN PROGRESS: many tests using @New beans
are still present, including the AtInject TCK runner.

### CODE REVIEW

**Comment by Ladicek** [comment]
Making this a draft, because we don't have (at least not yet) a branch for CDI 4.0 implementation. I just wanted to let you know this exists :-)

**Comment by manovotn** [comment]
> Making this a draft, because we don't have (at least not yet) a branch for CDI 4.0 implementation. I just wanted to let you know this exists :-)

Thanks, I am aware this needs doing. This and other changes from the deprecation PR as well. Once I am back next week I can create that branch. Or @mkouba can create it sooner.

**Comment by manovotn** [comment]
I have cherry-picked your commit into https://github.com/weld/core/pull/2383 where I want to create a stable buildable branch for next version. Closing this draft.

**Comment by Ladicek** [comment]
Cool, thanks!

**Pull request closed without merging**
