### PR TITLE
[WELD-2580] Ensure InjectionTarget#dispose(Object) method is called in ManagedBean implementation

### PR DESCRIPTION
**Pull request by ljnelson**
Fixes https://issues.jboss.org/browse/WELD-2580.

Signed-off-by: Laird Nelson <ljnelson@gmail.com>

### CODE REVIEW

**Comment by manovotn** [comment]
ok to test

**Comment by manovotn** [comment]
Theoretically, this should be alright.
After some poking around code I would say that any Producer that is actually backed by java class (as a bean) is based off `BasicInjectionTarget` which already overrides `dispose()` to no-op.
With this in mind, I haven't been able to think of a valid corner case that would be broken by this change. If anyone overrode IT at this point and declared some disposal method, then it has never been called and thus it's a bug in their code.

We'll also need a test for this (basically the content of issue reproducer made into an Arq. test).

**Comment by manovotn** [comment]
@ljnelson I am fine incorporating this change in next release. Though I would like a test that verifies this functionality. I have no problems adding one but since its your PR I was thinking you maybe want to do that?

**Comment by ljnelson** [comment]
@manovotn Yep; absolutely; just have to get to it.  😄

**Comment by ljnelson** [comment]
Hi, @manovotn; not sure where to start here; I see tests all over the place.  Maybe add something here (https://github.com/weld/core/blob/master/tests-arquillian/src/test/java/org/jboss/weld/tests/injectionTarget/InjectionTargetTest.java)?

**Comment by manovotn** [comment]
@ljnelson You were headed in right direction.
I'd create new package under https://github.com/weld/core/tree/master/tests-arquillian/src/test/java/org/jboss/weld/tests/injectionTarget, probably named `dispose`.

As for how to use the extension in a test, here is one example https://github.com/weld/core/blob/master/tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/qualifiers/SpiAddedQualifierTest.java#L35-L38

**Comment by ljnelson** [comment]
Hi, @manovotn; I've added a test.  CI failed for some reason, but building `weld/core` via `mvn clean install` works for me.

**Comment by manovotn** [comment]
@ljnelson the failure happens when running in container tests - that means against actual WFLY server.
Can be reproduced by doing `export JBOSS_HOME=/path/to/wfly` and running tests with `-Dincontainer` parameter

**Comment by manovotn** [comment]
@ljnelson pushed a commit that should fix the test, let's see what CI has to say.
I think your original test only worked  incidentally because of how Arquillian operates outside of WFLY. Using `Instance` to obtain and destroy the bean should be a sure shot in all environments.

**Comment by manovotn** [comment]
Yeah, that worked! :)

**Pull request merged**
