### PR TITLE
First PR for WELD-1871 plus WELD-1853 minor

### PR DESCRIPTION
**Pull request by mkouba**
This is a first PR for WELD-1871. There will be probably much more - it's a long-term issue.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 4b0b30f64aa526d741366133bf5ff8e0bbb39046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 522 is now running using a merge of 4b0b30f64aa526d741366133bf5ff8e0bbb39046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/522

**Comment by weld-tester** [comment]
Build 522 outcome was SUCCESS using a merge of 4b0b30f64aa526d741366133bf5ff8e0bbb39046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/522
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/522

**Comment by weld-tester** [comment]
Triggering build using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 523 is now running using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/523

**Comment by weld-tester** [comment]
Build 523 outcome was FAILURE using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/523
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/523

**Comment by weld-tester** [comment]
Build 523 outcome was FAILURE using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/523
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/523

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 524 is now running using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/524

**Comment by weld-tester** [comment]
Build 524 outcome was SUCCESS using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/524
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/524

**Comment by weld-tester** [comment]
Build 524 outcome was SUCCESS using a merge of 8fa3157089824fa36ff805c749564bae75384693 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/524
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/524

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
