### PR TITLE
Testing CI

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 439b31de0c226248a01874ed58f63589983d52df on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 625 outcome was FAILURE using a merge of 439b31de0c226248a01874ed58f63589983d52df on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/625
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/625

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 439b31de0c226248a01874ed58f63589983d52df on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 638 outcome was FAILURE using a merge of 439b31de0c226248a01874ed58f63589983d52df on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/638
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/638

**Comment by weld-tester** [comment]
Triggering build using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 644 is now running using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/644

**Comment by weld-tester** [comment]
Build 644 outcome was FAILURE using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/644
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/644

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 646 is now running using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/646

**Comment by weld-tester** [comment]
Build 646 outcome was FAILURE using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/646
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/646

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 649 is now running using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/649

**Comment by weld-tester** [comment]
Build 649 outcome was SUCCESS using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/649
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/649

**Comment by weld-tester** [comment]
Build 649 outcome was SUCCESS using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/649
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/649

**Comment by weld-tester** [comment]
Build 649 outcome was SUCCESS using a merge of 65b9c350663d894a73060de125e9b744c77b4ecf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/649
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/649

**Pull request closed without merging**
