### PR TITLE
Change the default value of org.jboss.weld.resolution.cacheSize to 65536

### PR DESCRIPTION
**Pull request by mkouba**
- also fix documentation

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 8223c645d8d856dc5c9e70353e71bf8b4041e7d1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 785 is now running using a merge of 8223c645d8d856dc5c9e70353e71bf8b4041e7d1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/785

**Comment by weld-tester** [comment]
Build 785 outcome was SUCCESS using a merge of 8223c645d8d856dc5c9e70353e71bf8b4041e7d1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/785
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/785

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
