### PR TITLE
Fix Probe producer test.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 44a8884664fef93ca0be96da09ddd9f51bcee343 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 794 is now running using a merge of 44a8884664fef93ca0be96da09ddd9f51bcee343 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/794

**Comment by weld-tester** [comment]
Build 794 outcome was SUCCESS using a merge of 44a8884664fef93ca0be96da09ddd9f51bcee343 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/794
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/794

**Comment by weld-tester** [comment]
Build 794 outcome was SUCCESS using a merge of 44a8884664fef93ca0be96da09ddd9f51bcee343 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/794
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/794

**Comment by weld-tester** [comment]
Build 794 outcome was SUCCESS using a merge of 44a8884664fef93ca0be96da09ddd9f51bcee343 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/794
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/794

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
