### PR TITLE
[BZ-1225378] Backport WELD-1607

### PR DESCRIPTION
**Pull request by baranowb**
No upstream required( change is already in 2.2+)
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1225378

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 803 is now running using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Build 803 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Build 803 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Build 803 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Build 803 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Build 803 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Build 803 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Build 803 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/803
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/803

**Comment by weld-tester** [comment]
Triggering build using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 828 is now running using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/828

**Comment by weld-tester** [comment]
Build 828 outcome was SUCCESS using a merge of 2842de8dfe6e528655c7d779f1450977cdd037d3 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/828
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/828

**Comment by jharting** [comment]
A log message needs to be added to `context_en.properties` for the new key.

**Comment by jharting** [comment]
Merged, thanks

**Pull request closed without merging**
