### PR TITLE
Mostly disposer methods performance optimizations

### PR DESCRIPTION
**Pull request by mkouba**
This is not ready to merge yet.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f159ede995793f249271332e92b94545b86f7acf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 534 is now running using a merge of f159ede995793f249271332e92b94545b86f7acf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/534

**Comment by weld-tester** [comment]
Build 534 outcome was SUCCESS using a merge of f159ede995793f249271332e92b94545b86f7acf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/534
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/534

**Comment by weld-tester** [comment]
Build 534 outcome was SUCCESS using a merge of f159ede995793f249271332e92b94545b86f7acf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/534
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/534

**Comment by weld-tester** [comment]
Build 534 outcome was SUCCESS using a merge of f159ede995793f249271332e92b94545b86f7acf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/534
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/534

**Comment by weld-tester** [comment]
Build 534 outcome was SUCCESS using a merge of f159ede995793f249271332e92b94545b86f7acf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/534
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/534

**Comment by weld-tester** [comment]
Build 534 outcome was SUCCESS using a merge of f159ede995793f249271332e92b94545b86f7acf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/534
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/534

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
