### PR TITLE
Backporting WELD-1853 and WELD-1871

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 499 is now running using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by weld-tester** [comment]
Build 499 outcome was SUCCESS using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by weld-tester** [comment]
Build 499 outcome was SUCCESS using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by weld-tester** [comment]
Build 499 outcome was SUCCESS using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by weld-tester** [comment]
Build 499 outcome was SUCCESS using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by weld-tester** [comment]
Build 499 outcome was SUCCESS using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by weld-tester** [comment]
Build 499 outcome was SUCCESS using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by weld-tester** [comment]
Build 499 outcome was SUCCESS using a merge of e31468675170e6c5d802ebc53434ff602e8f5c7d on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/499
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/499

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 01067ad2fd9c2777cfb3563952d97d59aecaf2b3 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 518 outcome was FAILURE using a merge of 01067ad2fd9c2777cfb3563952d97d59aecaf2b3 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/518
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/518

**Comment by weld-tester** [comment]
Triggering build using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 519 is now running using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/519

**Comment by weld-tester** [comment]
Build 519 outcome was SUCCESS using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/519
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/519

**Comment by weld-tester** [comment]
Build 519 outcome was SUCCESS using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/519
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/519

**Comment by weld-tester** [comment]
Build 519 outcome was SUCCESS using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/519
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/519

**Comment by weld-tester** [comment]
Build 519 outcome was SUCCESS using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/519
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/519

**Comment by weld-tester** [comment]
Triggering build using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 547 outcome was SUCCESS using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/547
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/547

**Comment by weld-tester** [comment]
Build 547 outcome was SUCCESS using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/547
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/547

**Comment by weld-tester** [comment]
Build 547 outcome was SUCCESS using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/547
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/547

**Comment by weld-tester** [comment]
Triggering build using a merge of efbdcec7a5d8e33fe7b64bb95f8425e626410115 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Triggering build using a merge of deb4f7b451965246b4661889860aa76129034abb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 749 outcome was FAILURE using a merge of deb4f7b451965246b4661889860aa76129034abb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/749
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/749

**Comment by weld-tester** [comment]
Triggering build using a merge of 967624adc2b6b1202f14b2ef50f63c933c7560ea on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 750 is now running using a merge of 967624adc2b6b1202f14b2ef50f63c933c7560ea on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/750

**Comment by weld-tester** [comment]
Build 750 outcome was SUCCESS using a merge of 967624adc2b6b1202f14b2ef50f63c933c7560ea on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/750
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/750

**Comment by mkouba** [comment]
@jharting This PR is ready for revision/merge again...

**Comment by weld-tester** [comment]
Build 750 outcome was SUCCESS using a merge of 967624adc2b6b1202f14b2ef50f63c933c7560ea on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/750
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/750

**Comment by weld-tester** [comment]
Build 750 outcome was SUCCESS using a merge of 967624adc2b6b1202f14b2ef50f63c933c7560ea on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/750
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/750

**Comment by weld-tester** [comment]
Build 750 outcome was SUCCESS using a merge of 967624adc2b6b1202f14b2ef50f63c933c7560ea on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/750
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/750

**Comment by weld-tester** [comment]
Build 750 outcome was SUCCESS using a merge of 967624adc2b6b1202f14b2ef50f63c933c7560ea on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/750
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/750

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
