### PR TITLE
Upgrade TCK and Arquillian versions.

### PR DESCRIPTION
**Pull request by tremes**
Conflicts:
	pom.xml

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 15ebd6d68095b0756c59d6bdd0f523dbd5cb3a51 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 771 is now running using a merge of 15ebd6d68095b0756c59d6bdd0f523dbd5cb3a51 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/771

**Comment by weld-tester** [comment]
Build 771 outcome was SUCCESS using a merge of 15ebd6d68095b0756c59d6bdd0f523dbd5cb3a51 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/771
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/771

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
