### PR TITLE
WELD-1940 Backport docs

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 43a311e81f4028fedea83ff9fa023162fe8a5ce2 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 808 is now running using a merge of 43a311e81f4028fedea83ff9fa023162fe8a5ce2 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/808

**Comment by weld-tester** [comment]
Build 808 outcome was SUCCESS using a merge of 43a311e81f4028fedea83ff9fa023162fe8a5ce2 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/808
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/808

**Comment by weld-tester** [comment]
Build 808 outcome was SUCCESS using a merge of 43a311e81f4028fedea83ff9fa023162fe8a5ce2 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/808
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/808

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
