### PR TITLE
Weld Servlet - use WEB-INF/classes BeanManager for EL resolution

### PR DESCRIPTION
**Pull request by mkouba**
- if not possible, take the first one available (current behaviour)

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7923726aaeafe59eb12a09955ec871e7213a8998 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 508 is now running using a merge of 7923726aaeafe59eb12a09955ec871e7213a8998 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/508

**Comment by weld-tester** [comment]
Build 508 outcome was SUCCESS using a merge of 7923726aaeafe59eb12a09955ec871e7213a8998 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/508
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/508

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
