### PR TITLE
WELD-2144 add dependency to weld-core-jsf

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by mkouba** [comment]
Maybe we should also revise `org.jboss.weld.servlet:weld-servlet` pom.xml... weld-core-impl and weld-core-jsf seem to be redundant (but rather double check this assumption ;-).

**Comment by tremes** [comment]
Yes I realized that. Both should be likely redundant.

**Comment by tremes** [comment]
Hm weird SE tests failure at JDK7....

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
