### PR TITLE
WELD-1881 Probe - handle flat deployment correctly

### PR DESCRIPTION
**Pull request by mkouba**
Plus some app.js formatting.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e94b84ed8c737fc5c69fe58ede085fee386f59d0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 535 is now running using a merge of e94b84ed8c737fc5c69fe58ede085fee386f59d0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/535

**Comment by weld-tester** [comment]
Build 535 outcome was SUCCESS using a merge of e94b84ed8c737fc5c69fe58ede085fee386f59d0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/535
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/535

**Comment by weld-tester** [comment]
Build 535 outcome was SUCCESS using a merge of e94b84ed8c737fc5c69fe58ede085fee386f59d0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/535
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/535

**Comment by weld-tester** [comment]
Build 535 outcome was SUCCESS using a merge of e94b84ed8c737fc5c69fe58ede085fee386f59d0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/535
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/535

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
