### PR TITLE
Testing Jenkins PR integration

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of bee9ad465243d9399ca9a79cafb4f00b4e5dd9f9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Build 965 is now running using a merge of bee9ad465243d9399ca9a79cafb4f00b4e5dd9f9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/965

**Comment by weld-tester** [comment]
Build 965 outcome was SUCCESS using a merge of bee9ad465243d9399ca9a79cafb4f00b4e5dd9f9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/965
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/965

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of bee9ad465243d9399ca9a79cafb4f00b4e5dd9f9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 966 is now running using a merge of bee9ad465243d9399ca9a79cafb4f00b4e5dd9f9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/966

**Comment by weld-tester** [comment]
Triggering build using a merge of e1b96dd05243bbddb205dc53ea0c8fe4d24421e8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 968 outcome was FAILURE using a merge of e1b96dd05243bbddb205dc53ea0c8fe4d24421e8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/968
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/968

**Comment by jharting** [comment]
retest this please

**Pull request closed without merging**
