### PR TITLE
Weld SE, Servlet - set bean deployment archives accessibility clearly

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 816ca497d73218f5f2575d601a9915789e014521 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 715 is now running using a merge of 816ca497d73218f5f2575d601a9915789e014521 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/715

**Comment by weld-tester** [comment]
Build 715 outcome was SUCCESS using a merge of 816ca497d73218f5f2575d601a9915789e014521 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/715
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/715

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
