### PR TITLE
Probe - various minor changes to observer pages

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d04820df05b05d61bd51cc1e54a44b8cb03bfe69 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 444 is now running using a merge of d04820df05b05d61bd51cc1e54a44b8cb03bfe69 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/444

**Comment by mkouba** [comment]
Looks good. However, I'm not so sure whether it's a good idea to include experimental features (CDI 2.0 features in general) at this stage of development, i.e. `Prioritized`. I mean it will complicate the potential backporting of probe into 2.2 branch.

**Comment by weld-tester** [comment]
Build 444 outcome was SUCCESS using a merge of d04820df05b05d61bd51cc1e54a44b8cb03bfe69 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/444
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/444

**Comment by weld-tester** [comment]
Build 444 outcome was SUCCESS using a merge of d04820df05b05d61bd51cc1e54a44b8cb03bfe69 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/444
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/444

**Comment by weld-tester** [comment]
Build 444 outcome was SUCCESS using a merge of d04820df05b05d61bd51cc1e54a44b8cb03bfe69 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/444
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/444

**Comment by weld-tester** [comment]
Build 444 outcome was SUCCESS using a merge of d04820df05b05d61bd51cc1e54a44b8cb03bfe69 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/444
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/444

**Comment by weld-tester** [comment]
Build 444 outcome was SUCCESS using a merge of d04820df05b05d61bd51cc1e54a44b8cb03bfe69 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/444
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/444

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
