### PR TITLE
WELD-1798 revise JAX WS tests.

### PR DESCRIPTION
**Pull request by tremes**
Done same as in TCK. It could be merged to 2.2 and 1.1 as well.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 9711bc0ae6b31d8c31bfc1d1dc88551c191de96a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 672 is now running using a merge of 9711bc0ae6b31d8c31bfc1d1dc88551c191de96a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/672

**Comment by weld-tester** [comment]
Build 672 outcome was SUCCESS using a merge of 9711bc0ae6b31d8c31bfc1d1dc88551c191de96a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/672
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/672

**Comment by weld-tester** [comment]
Build 672 outcome was SUCCESS using a merge of 9711bc0ae6b31d8c31bfc1d1dc88551c191de96a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/672
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/672

**Comment by jharting** [comment]
Please send a separate PR for 1.1

**Comment by tremes** [comment]
Created https://github.com/weld/core/pull/939

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
