### PR TITLE
WELD-1976 Part 2

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e2559946658369426dcfd58c39fbe0d0cb98fe26 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 946 is now running using a merge of e2559946658369426dcfd58c39fbe0d0cb98fe26 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/946

**Comment by weld-tester** [comment]
Build 946 outcome was SUCCESS using a merge of e2559946658369426dcfd58c39fbe0d0cb98fe26 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/946
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/946

**Comment by weld-tester** [comment]
Triggering build using a merge of 5ada53b901d1423a62c2499ee055e2b659466974 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 947 outcome was FAILURE using a merge of 5ada53b901d1423a62c2499ee055e2b659466974 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/947
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/947

**Comment by weld-tester** [comment]
Triggering build using a merge of 306f081408eb420da34c5ba0a0168d94f65998d9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 948 outcome was FAILURE using a merge of 306f081408eb420da34c5ba0a0168d94f65998d9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/948
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/948

**Comment by weld-tester** [comment]
Build 948 outcome was FAILURE using a merge of 306f081408eb420da34c5ba0a0168d94f65998d9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/948
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/948

**Comment by weld-tester** [comment]
Build 948 outcome was FAILURE using a merge of 306f081408eb420da34c5ba0a0168d94f65998d9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/948
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/948

**Comment by weld-tester** [comment]
Triggering build using a merge of 1315ab492dc3047ddd80f9011236988e85056e14 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 949 outcome was FAILURE using a merge of 1315ab492dc3047ddd80f9011236988e85056e14 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/949
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/949

**Comment by weld-tester** [comment]
Triggering build using a merge of cf327abb17f68c2fef5ffd1c6557dcfc9c79714a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 950 is now running using a merge of cf327abb17f68c2fef5ffd1c6557dcfc9c79714a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/950

**Comment by weld-tester** [comment]
Build 950 outcome was FAILURE using a merge of cf327abb17f68c2fef5ffd1c6557dcfc9c79714a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/950
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/950

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of cf327abb17f68c2fef5ffd1c6557dcfc9c79714a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 951 is now running using a merge of cf327abb17f68c2fef5ffd1c6557dcfc9c79714a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/951

**Comment by weld-tester** [comment]
Build 951 outcome was SUCCESS using a merge of cf327abb17f68c2fef5ffd1c6557dcfc9c79714a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/951
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/951

**Pull request merged**
