### PR TITLE
CreationalContextTest - minor improvement

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of b4e7d8fb503e466702ca5500f6bf9e0c03e1bf7a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 930 is now running using a merge of b4e7d8fb503e466702ca5500f6bf9e0c03e1bf7a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/930

**Comment by weld-tester** [comment]
Build 930 outcome was SUCCESS using a merge of b4e7d8fb503e466702ca5500f6bf9e0c03e1bf7a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/930
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/930

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
