### PR TITLE
This should be unneccessary in tck runner.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 718 is now running using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/718

**Comment by weld-tester** [comment]
Build 718 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/718
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/718

**Comment by jharting** [comment]
Should this also be backported to 2.2?

**Comment by tremes** [comment]
Yes it could be backported.

**Comment by jharting** [comment]
In that case `cdi-tck-ext-lib` version should not be hardcoded but should match tck12/tck20 profile, shouldn't it?

**Comment by weld-tester** [comment]
Build 718 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/718
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/718

**Comment by weld-tester** [comment]
Build 718 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/718
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/718

**Comment by weld-tester** [comment]
Triggering build using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 744 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/744
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/744

**Comment by weld-tester** [comment]
Build 744 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/744
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/744

**Comment by weld-tester** [comment]
Build 744 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/744
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/744

**Comment by weld-tester** [comment]
Triggering build using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 770 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/770
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/770

**Comment by jharting** [comment]
We'll probably need to make the update script configurable (the version of cdi-tck-lib).

**Comment by weld-tester** [comment]
Build 770 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/770
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/770

**Comment by weld-tester** [comment]
Triggering build using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 820 outcome was SUCCESS using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/820
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/820

**Comment by weld-tester** [comment]
Triggering build using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 847 outcome was FAILURE using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/847
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/847

**Comment by weld-tester** [comment]
Build 847 outcome was FAILURE using a merge of c109b7388f7bfda1d370a40cdffb21c1bc488eec on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/847
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/847

**Pull request closed without merging**
