### PR TITLE
Rebasefindbugs

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of c185bd0813884d6a3483da78d67889329d78c457 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 539 is now running using a merge of c185bd0813884d6a3483da78d67889329d78c457 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/539

**Comment by weld-tester** [comment]
Build 539 outcome was SUCCESS using a merge of c185bd0813884d6a3483da78d67889329d78c457 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/539
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/539

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
Out of date

**Pull request closed without merging**
