### PR TITLE
[WELD-1999] ClassNotFoundException thrown when deserializing a bean u…

### PR DESCRIPTION
**Pull request by spyrkob**
…sing InjectionPoint

FieldInjectionPoint.SerializationProxy uses BeanManager to load target
class instead of using default ResourceLoader

### CODE REVIEW

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
This patch fixes the problem with FieldInjectionPoint but the same problem may arise with ParameterInjectionPoint. It would be therefore be better to propagate the BeanManager field one level further to WeldInjectionPointSerializationProxy and alter the logic of the `getService()` method to use this BeanManager.

**Comment by spyrkob** [comment]
Moved the BeanManager and updated other InjectionPoint classes. I could only reproduce the issue using the field injection though.

**Comment by spyrkob** [comment]
@jharting could you take a look at the updated code and let me know if it needs any more changes?

**Comment by jharting** [comment]
ok to test

**Comment by jharting** [comment]
This change causes test failures:
```
java.lang.NullPointerException
        at org.jboss.weld.injection.WeldInjectionPoint$WeldInjectionPointSerializationProxy.getService(WeldInjectionPoint.java:65)
        at org.jboss.weld.injection.WeldInjectionPoint$WeldInjectionPointSerializationProxy.<init>(WeldInjectionPoint.java:43)
        at org.jboss.weld.injection.FieldInjectionPoint$SerializationProxy.<init>(FieldInjectionPoint.java:204)
        at org.jboss.weld.injection.FieldInjectionPoint.writeReplace(FieldInjectionPoint.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1075)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
```

**Comment by spyrkob** [comment]
I was sure I run those tests before pushing... sorry

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
