### PR TITLE
WELD-1992 throw ISE on already shutdowned SE container.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 919 is now running using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/919

**Comment by weld-tester** [comment]
Build 919 outcome was SUCCESS using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/919
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/919

**Comment by weld-tester** [comment]
Build 919 outcome was SUCCESS using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/919
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/919

**Comment by weld-tester** [comment]
Build 919 outcome was SUCCESS using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/919
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/919

**Comment by weld-tester** [comment]
Build 919 outcome was SUCCESS using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/919
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/919

**Comment by weld-tester** [comment]
Triggering build using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 941 is now running using a merge of c79c4102a6afac04cd9dabd2074f293f9d41d0e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/941

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
