### PR TITLE
Fix update jboss script.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 581 is now running using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/581

**Comment by weld-tester** [comment]
Build 581 outcome was FAILURE using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/581
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/581

**Comment by tremes** [comment]
Hmm this is broken in case of updating from e.g. Alpha4 - separate probe module and one core-impl jar.

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 582 is now running using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/582

**Comment by weld-tester** [comment]
Build 582 outcome was SUCCESS using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/582
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/582

**Comment by weld-tester** [comment]
Build 582 outcome was SUCCESS using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/582
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/582

**Comment by weld-tester** [comment]
Build 582 outcome was SUCCESS using a merge of d84534761096e2baffbb0384240324ae3c5153c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/582
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/582

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
