### PR TITLE
Probe fixes and improvements

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e777ea2129f27405d60bbf58ad7a06802478687b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 516 is now running using a merge of e777ea2129f27405d60bbf58ad7a06802478687b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/516

**Comment by weld-tester** [comment]
Build 516 outcome was SUCCESS using a merge of e777ea2129f27405d60bbf58ad7a06802478687b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/516
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/516

**Comment by weld-tester** [comment]
Build 516 outcome was SUCCESS using a merge of e777ea2129f27405d60bbf58ad7a06802478687b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/516
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/516

**Comment by weld-tester** [comment]
Build 516 outcome was SUCCESS using a merge of e777ea2129f27405d60bbf58ad7a06802478687b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/516
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/516

**Comment by jharting** [comment]
Looks like this needs a rebase

**Comment by mkouba** [comment]
@jharting rebased :-) retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of fcf86919724c7fa311389eb81831418fa85f842a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 525 is now running using a merge of fcf86919724c7fa311389eb81831418fa85f842a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/525

**Comment by weld-tester** [comment]
Build 525 outcome was SUCCESS using a merge of fcf86919724c7fa311389eb81831418fa85f842a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/525
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/525

**Comment by weld-tester** [comment]
Build 525 outcome was SUCCESS using a merge of fcf86919724c7fa311389eb81831418fa85f842a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/525
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/525

**Pull request merged**
