### PR TITLE
Make examples compilable again.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of baed88d4f7c8ebcc730753dff1cd9c040ab2d475 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 804 is now running using a merge of baed88d4f7c8ebcc730753dff1cd9c040ab2d475 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/804

**Comment by weld-tester** [comment]
Build 804 outcome was SUCCESS using a merge of baed88d4f7c8ebcc730753dff1cd9c040ab2d475 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/804
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/804

**Comment by weld-tester** [comment]
Build 804 outcome was SUCCESS using a merge of baed88d4f7c8ebcc730753dff1cd9c040ab2d475 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/804
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/804

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
