### PR TITLE
WELD-1936 Expose BeanBuilder in Weld builder

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 2cdf3e5dfbd6da69b2ea46fd35d8329d65f468c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 733 outcome was FAILURE using a merge of 2cdf3e5dfbd6da69b2ea46fd35d8329d65f468c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/733
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/733

**Comment by weld-tester** [comment]
Triggering build using a merge of 40aa0db44772fc73ae614d9c4d4ccd4d67d04169 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 734 outcome was FAILURE using a merge of 40aa0db44772fc73ae614d9c4d4ccd4d67d04169 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/734
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/734

**Comment by weld-tester** [comment]
Triggering build using a merge of 8057e28be298de03b44de8238a0a1272e404ce61 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 735 is now running using a merge of 8057e28be298de03b44de8238a0a1272e404ce61 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/735

**Comment by weld-tester** [comment]
Build 735 outcome was SUCCESS using a merge of 8057e28be298de03b44de8238a0a1272e404ce61 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/735
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/735

**Comment by weld-tester** [comment]
Build 735 outcome was SUCCESS using a merge of 8057e28be298de03b44de8238a0a1272e404ce61 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/735
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/735

**Comment by jharting** [comment]
What are the benefits of obtaining BM and creating attributes, producers, etc. within the readAnnotatedType() method? I find the current `if (ready) then foo else bar` rather complex and think that we could defer it always to `build()` phase

**Comment by jharting** [comment]
Also, DeploymentFinder looks like a nice abstraction - we could abstract it into a top-level class / interface which would simplify code in other places also. For the Weld SE use-case we could use a mutable implementation that gets updated once WeldStartup is available.

**Comment by mkouba** [comment]
> What are the benefits of obtaining BM...

`BeanBuilder.read()` is currently a replacement operation. So if you read the `AnnotatedType` immediately it's possible to do something like:

```
afterBeanDiscovery.addBean().read(fooAnnotatedType).addType(Bar.class);
```
If we always defer the read operation, we would have to merge the attributes somehow. And don't find this very intuitive. On the other hand I agree that it's not  consistent now.

**Comment by mkouba** [comment]
> Also, DeploymentFinder looks like a nice abstraction...

OK. I will try to extract the interface.

**Comment by mkouba** [comment]
@jharting When I think about it - it does not make much sense to support `BeanBuilder.read()` in Weld SE. There will be no `BeanManager` to create `AnnotatedType` or `BeanAttributes`. What if we forbid the use of these read methods in Weld SE completely?

**Comment by jharting** [comment]
`afterBeanDiscovery.addBean().read(fooAnnotatedType).addType(Bar.class);`

The set of type that comes from fooAnnotatedType is merged with Bar anyway so I don't think it would be very counter-intuitive to modify read() operations to do additions instead of replacement. It is a *builder* after all.

As for read() operations you are right that we do not necessarily need them in SE.

**Comment by weld-tester** [comment]
Triggering build using a merge of 84440c129865cb8d3e8e09f8ab310ffce2f68ed4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 737 outcome was FAILURE using a merge of 84440c129865cb8d3e8e09f8ab310ffce2f68ed4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/737
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/737

**Comment by jharting** [comment]
I like beanbuilder changes. As for BeanDeploymentFinder since WeldStartup already holds the 4 references required for finding a BeanDeployment I would instead BeanDeploymentFinder introduce a single-method interface and have WeldStartup implement it.

```java
public synchronized BeanDeploymentFinder getBeanDeploymentFinder() {
    return weldStartup;
}
```
This duplicates less "holder" code. Also since the clients use the BeanDeploymentFinder and not WeldStartup directly we can always change what we return from `getBeanDeploymentFinder()` if we need to

**Comment by mkouba** [comment]
The pull request for API: https://github.com/weld/api/pull/22

**Comment by weld-tester** [comment]
Triggering build using a merge of 2cb621805aa7daa3d0a75455e39b365fc1a577ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 741 outcome was FAILURE using a merge of 2cb621805aa7daa3d0a75455e39b365fc1a577ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/741
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/741

**Comment by weld-tester** [comment]
Build 741 outcome was FAILURE using a merge of 2cb621805aa7daa3d0a75455e39b365fc1a577ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/741
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/741

**Comment by weld-tester** [comment]
Build 741 outcome was FAILURE using a merge of 2cb621805aa7daa3d0a75455e39b365fc1a577ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/741
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/741

**Comment by weld-tester** [comment]
Build 741 outcome was FAILURE using a merge of 2cb621805aa7daa3d0a75455e39b365fc1a577ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/741
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/741

**Comment by weld-tester** [comment]
Triggering build using a merge of 650451bb6b59f32f45adb0e73cd3e4f91ab12597 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 746 is now running using a merge of 650451bb6b59f32f45adb0e73cd3e4f91ab12597 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/746

**Comment by weld-tester** [comment]
Build 746 outcome was SUCCESS using a merge of 650451bb6b59f32f45adb0e73cd3e4f91ab12597 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/746
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/746

**Comment by weld-tester** [comment]
Build 746 outcome was SUCCESS using a merge of 650451bb6b59f32f45adb0e73cd3e4f91ab12597 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/746
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/746

**Comment by weld-tester** [comment]
Build 746 outcome was SUCCESS using a merge of 650451bb6b59f32f45adb0e73cd3e4f91ab12597 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/746
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/746

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
