### PR TITLE
WELD-1871 Next part

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 680e61d49cc246205f2bd1bd49c3e9f8de43c42c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 823 is now running using a merge of 680e61d49cc246205f2bd1bd49c3e9f8de43c42c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/823

**Comment by weld-tester** [comment]
Build 823 outcome was SUCCESS using a merge of 680e61d49cc246205f2bd1bd49c3e9f8de43c42c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/823
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/823

**Comment by weld-tester** [comment]
Build 823 outcome was SUCCESS using a merge of 680e61d49cc246205f2bd1bd49c3e9f8de43c42c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/823
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/823

**Comment by weld-tester** [comment]
Build 823 outcome was SUCCESS using a merge of 680e61d49cc246205f2bd1bd49c3e9f8de43c42c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/823
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/823

**Comment by weld-tester** [comment]
Build 823 outcome was SUCCESS using a merge of 680e61d49cc246205f2bd1bd49c3e9f8de43c42c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/823
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/823

**Comment by weld-tester** [comment]
Build 823 outcome was SUCCESS using a merge of 680e61d49cc246205f2bd1bd49c3e9f8de43c42c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/823
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/823

**Comment by weld-tester** [comment]
Triggering build using a merge of a833264be12b44f2bfe4090c79401971a4d3c658 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 834 is now running using a merge of a833264be12b44f2bfe4090c79401971a4d3c658 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/834

**Comment by weld-tester** [comment]
Build 834 outcome was SUCCESS using a merge of a833264be12b44f2bfe4090c79401971a4d3c658 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/834
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/834

**Comment by weld-tester** [comment]
Build 834 outcome was SUCCESS using a merge of a833264be12b44f2bfe4090c79401971a4d3c658 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/834
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/834

**Comment by weld-tester** [comment]
Build 834 outcome was SUCCESS using a merge of a833264be12b44f2bfe4090c79401971a4d3c658 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/834
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/834

**Comment by weld-tester** [comment]
Triggering build using a merge of 910c8d0b9db5c8508d192bf22396bf258e3e3434 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 838 is now running using a merge of 910c8d0b9db5c8508d192bf22396bf258e3e3434 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/838

**Comment by weld-tester** [comment]
Build 838 outcome was SUCCESS using a merge of 910c8d0b9db5c8508d192bf22396bf258e3e3434 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/838
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/838

**Comment by weld-tester** [comment]
Build 838 outcome was SUCCESS using a merge of 910c8d0b9db5c8508d192bf22396bf258e3e3434 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/838
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/838

**Comment by weld-tester** [comment]
Build 838 outcome was SUCCESS using a merge of 910c8d0b9db5c8508d192bf22396bf258e3e3434 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/838
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/838

**Comment by weld-tester** [comment]
Build 838 outcome was SUCCESS using a merge of 910c8d0b9db5c8508d192bf22396bf258e3e3434 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/838
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/838

**Comment by weld-tester** [comment]
Triggering build using a merge of d91d31fadeb1f1908896fa9bcb5dd18c67283121 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 840 is now running using a merge of d91d31fadeb1f1908896fa9bcb5dd18c67283121 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/840

**Comment by weld-tester** [comment]
Build 840 outcome was SUCCESS using a merge of d91d31fadeb1f1908896fa9bcb5dd18c67283121 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/840
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/840

**Comment by weld-tester** [comment]
Build 840 outcome was SUCCESS using a merge of d91d31fadeb1f1908896fa9bcb5dd18c67283121 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/840
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/840

**Comment by weld-tester** [comment]
Triggering build using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 846 outcome was FAILURE using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/846
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/846

**Comment by weld-tester** [comment]
Build 846 outcome was FAILURE using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/846
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/846

**Comment by weld-tester** [comment]
Build 846 outcome was FAILURE using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/846
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/846

**Comment by weld-tester** [comment]
Build 846 outcome was FAILURE using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/846
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/846

**Comment by weld-tester** [comment]
Build 846 outcome was FAILURE using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/846
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/846

**Comment by weld-tester** [comment]
Build 846 outcome was FAILURE using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/846
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/846

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 849 is now running using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/849

**Comment by weld-tester** [comment]
Build 849 outcome was SUCCESS using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/849
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/849

**Comment by weld-tester** [comment]
Build 849 outcome was SUCCESS using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/849
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/849

**Comment by mkouba** [comment]
I will create a separate PR for 2.3 branch if there are no objections..

**Comment by jharting** [comment]
yes, go ahead

**Comment by mkouba** [comment]
@jharting Then please merge https://github.com/weld/core/pull/1028 first.

**Comment by weld-tester** [comment]
Build 849 outcome was SUCCESS using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/849
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/849

**Comment by weld-tester** [comment]
Build 849 outcome was SUCCESS using a merge of a7a49959c137e06b1a702215d8d85f4d9ceb7303 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/849
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/849

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
