### PR TITLE
WELD-1853 Implement Formats.getLineNumber()

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d4c462e96813186292ff50c1ae296d10f14ee0d2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 491 outcome was FAILURE using a merge of d4c462e96813186292ff50c1ae296d10f14ee0d2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/491
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/491

**Comment by mkouba** [comment]
A checkstyle error :-(

**Comment by weld-tester** [comment]
Triggering build using a merge of dd51900577dcaf867b53f82305f12fbfba6aea85 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 493 is now running using a merge of dd51900577dcaf867b53f82305f12fbfba6aea85 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/493

**Comment by weld-tester** [comment]
Build 493 outcome was SUCCESS using a merge of dd51900577dcaf867b53f82305f12fbfba6aea85 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/493
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/493

**Comment by weld-tester** [comment]
Build 493 outcome was SUCCESS using a merge of dd51900577dcaf867b53f82305f12fbfba6aea85 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/493
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/493

**Comment by jharting** [comment]
It would be nice to backport this to 2.2 sooner or later. Some of the Java 7/8 constructs may make that painful. Otherwise, this looks good to merge. Do not forget to add WELD-1853 reference in commit messages and remove "an attempt to" part :-)

**Comment by mkouba** [comment]
> Some of the Java 7/8 constructs may make that painful.

Ah, you mean the try-with-resources statement. Ok, no problem. 

> Do not forget to add WELD-1853 reference...

Ok, I wasn't aware of this issue.

**Comment by jharting** [comment]
> Ah, you mean the try-with-resources statement. Ok, no problem.

Also Executable. The best way to verify is to send a PR for 2.2 right away :-)

**Comment by mkouba** [comment]
I will do a separate PR for 2.2 branch.

**Comment by weld-tester** [comment]
Triggering build using a merge of 1068a5ca757c8e7bb833f2d93884fb6fc6b20925 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 498 is now running using a merge of 1068a5ca757c8e7bb833f2d93884fb6fc6b20925 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/498

**Comment by weld-tester** [comment]
Build 498 outcome was SUCCESS using a merge of 1068a5ca757c8e7bb833f2d93884fb6fc6b20925 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/498
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/498

**Comment by weld-tester** [comment]
Build 498 outcome was SUCCESS using a merge of 1068a5ca757c8e7bb833f2d93884fb6fc6b20925 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/498
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/498

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
