### PR TITLE
Add profile in TCK runner for executing in SE container.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 88df9b602283ccc1a9d63320fee8dc7cc937ebd8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 917 is now running using a merge of 88df9b602283ccc1a9d63320fee8dc7cc937ebd8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/917

**Comment by weld-tester** [comment]
Build 917 outcome was SUCCESS using a merge of 88df9b602283ccc1a9d63320fee8dc7cc937ebd8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/917
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/917

**Comment by weld-tester** [comment]
Triggering build using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 933 is now running using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by weld-tester** [comment]
Build 933 outcome was SUCCESS using a merge of e4ec7961775d7525dd3f9e00382ad46c87221301 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/933
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/933

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
