### PR TITLE
WELD-1909 Split out EJB integration

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 238bb51ba06ef41176b7a8a3544f63424e65c593 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 653 outcome was FAILURE using a merge of 238bb51ba06ef41176b7a8a3544f63424e65c593 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/653
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/653

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 238bb51ba06ef41176b7a8a3544f63424e65c593 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 654 outcome was FAILURE using a merge of 238bb51ba06ef41176b7a8a3544f63424e65c593 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/654
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/654

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 238bb51ba06ef41176b7a8a3544f63424e65c593 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Triggering build using a merge of 10e0b3ba0fb5a2b4caec13af89c4095908b087c4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 657 is now running using a merge of 10e0b3ba0fb5a2b4caec13af89c4095908b087c4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/657

**Comment by weld-tester** [comment]
Build 657 outcome was SUCCESS using a merge of 10e0b3ba0fb5a2b4caec13af89c4095908b087c4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/657
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/657

**Comment by weld-tester** [comment]
Build 657 outcome was SUCCESS using a merge of 10e0b3ba0fb5a2b4caec13af89c4095908b087c4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/657
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/657

**Comment by weld-tester** [comment]
Build 657 outcome was SUCCESS using a merge of 10e0b3ba0fb5a2b4caec13af89c4095908b087c4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/657
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/657

**Pull request closed without merging**
