### PR TITLE
Change the default value of org.jboss.weld.resolution.cacheSize to 65536

### PR DESCRIPTION
**Pull request by mkouba**
- also fix documentation

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f9d84dc3162cf873de0a2fd9d5722a61601b0c8c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 784 is now running using a merge of f9d84dc3162cf873de0a2fd9d5722a61601b0c8c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/784

**Comment by weld-tester** [comment]
Build 784 outcome was SUCCESS using a merge of f9d84dc3162cf873de0a2fd9d5722a61601b0c8c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/784
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/784

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
