### PR TITLE
WELD-1985, WELD-1986, WELD-1989 (Probe)

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of b58d35b9c3d69658bc3808b6299bcb5b74637307 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 910 is now running using a merge of b58d35b9c3d69658bc3808b6299bcb5b74637307 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/910

**Comment by weld-tester** [comment]
Build 910 outcome was SUCCESS using a merge of b58d35b9c3d69658bc3808b6299bcb5b74637307 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/910
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/910

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
