### PR TITLE
WELD-1870 - Probe - added profile for Tomcat embedded execution.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 1e2a32052a3f19cfcac38aace7b187542650a9e3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 538 is now running using a merge of 1e2a32052a3f19cfcac38aace7b187542650a9e3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/538

**Comment by weld-tester** [comment]
Build 538 outcome was SUCCESS using a merge of 1e2a32052a3f19cfcac38aace7b187542650a9e3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/538
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/538

**Comment by tremes** [comment]
The 71c0ba77a5ecafa45dbe4384f986e98a395ef2f5 commit merge please after https://github.com/weld/core/pull/885 is merged. Thank's

**Comment by weld-tester** [comment]
Triggering build using a merge of 71c0ba77a5ecafa45dbe4384f986e98a395ef2f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 544 outcome was FAILURE using a merge of 71c0ba77a5ecafa45dbe4384f986e98a395ef2f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/544
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/544

**Comment by weld-tester** [comment]
Build 544 outcome was FAILURE using a merge of 71c0ba77a5ecafa45dbe4384f986e98a395ef2f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/544
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/544

**Comment by weld-tester** [comment]
Build 544 outcome was FAILURE using a merge of 71c0ba77a5ecafa45dbe4384f986e98a395ef2f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/544
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/544

**Comment by weld-tester** [comment]
Build 544 outcome was FAILURE using a merge of 71c0ba77a5ecafa45dbe4384f986e98a395ef2f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/544
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/544

**Comment by weld-tester** [comment]
Triggering build using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 548 is now running using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/548

**Comment by weld-tester** [comment]
Build 548 outcome was FAILURE using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/548
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/548

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 549 is now running using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/549

**Comment by weld-tester** [comment]
Build 549 outcome was SUCCESS using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/549
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/549

**Comment by weld-tester** [comment]
Build 549 outcome was SUCCESS using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/549
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/549

**Comment by weld-tester** [comment]
Build 549 outcome was SUCCESS using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/549
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/549

**Comment by weld-tester** [comment]
Build 549 outcome was SUCCESS using a merge of 608de99d56adbdab0a6486a8bdc21672b8d7d9b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/549
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/549

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
