### PR TITLE
slight performance

### PR DESCRIPTION
**Pull request by otaviojava**
Improvements in the code to slight performance

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 11e78d7acc41a1e5e2bcedaee2e9cf67f46fd600 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 424 is now running using a merge of 11e78d7acc41a1e5e2bcedaee2e9cf67f46fd600 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/424

**Comment by weld-tester** [comment]
Build 424 outcome was SUCCESS using a merge of 11e78d7acc41a1e5e2bcedaee2e9cf67f46fd600 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/424
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/424

**Comment by jharting** [comment]
Out of date

**Pull request closed without merging**
