### PR TITLE
 CDI 2.0-EDR1, WELD-1978

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f59720b272204aaf348723c971be4afb30aebc65 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 907 is now running using a merge of f59720b272204aaf348723c971be4afb30aebc65 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/907

**Comment by weld-tester** [comment]
Build 907 outcome was SUCCESS using a merge of f59720b272204aaf348723c971be4afb30aebc65 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/907
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/907

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
