### PR TITLE
BZ-1388757 Backport WELD-1256 - AbstractConversationContext calls conversation.end() without checking if its transient

### PR DESCRIPTION
**Pull request by kurobako**
https://issues.jboss.org/browse/WELD-1256
https://github.com/weld/core/commit/ad3c7f997cd30130a96986598dfb9bf8db00de3a

### CODE REVIEW

**Comment by mkouba** [comment]
test this please

**Comment by kurobako** [comment]
Failed tests:   testInvalidatingSessionDestroysConversation(org.jboss.jsr299.tck.tests.context.conversation.InvalidatingSessionDestroysConversationTest)
07:35:46 
07:35:46 Tests run: 841, Failures: 1, Errors: 0, Skipped: 0

**Comment by kurobako** [comment]
test this please

**Comment by mkouba** [comment]
retest this please

**Comment by manovotn** [comment]
The fix looks alright, although we don't have a dedicated test for this and I am not sure how to simulate it.
Any chance for a reproducer app or a more info about usage @kurobako ?

**Comment by kurobako** [comment]
@manovotn https://issues.jboss.org/browse/WELD-1256?focusedCommentId=12733579&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12733579

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
