### PR TITLE
WELD-1907 Reset initialized flag during lazy conv. context activation

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 8fe488455fc974d1bde0f38dfd3337408b74165e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 599 outcome was FAILURE using a merge of 8fe488455fc974d1bde0f38dfd3337408b74165e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/599
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/599

**Comment by mkouba** [comment]
@jharting I think we should get this into 2.2.10.SP1 as well. WDYT?

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 8fe488455fc974d1bde0f38dfd3337408b74165e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 600 is now running using a merge of 8fe488455fc974d1bde0f38dfd3337408b74165e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/600

**Comment by weld-tester** [comment]
Build 600 outcome was SUCCESS using a merge of 8fe488455fc974d1bde0f38dfd3337408b74165e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/600
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/600

**Comment by weld-tester** [comment]
Triggering build using a merge of ca18959228263b14cd6cbde7946281516074a970 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 604 outcome was FAILURE using a merge of ca18959228263b14cd6cbde7946281516074a970 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/604
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/604

**Comment by weld-tester** [comment]
Triggering build using a merge of d9edd17cfbc8eda00c704e0172b9e76a71646738 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 605 is now running using a merge of d9edd17cfbc8eda00c704e0172b9e76a71646738 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/605

**Comment by weld-tester** [comment]
Build 605 outcome was SUCCESS using a merge of d9edd17cfbc8eda00c704e0172b9e76a71646738 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/605
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/605

**Comment by weld-tester** [comment]
Build 605 outcome was SUCCESS using a merge of d9edd17cfbc8eda00c704e0172b9e76a71646738 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/605
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/605

**Comment by weld-tester** [comment]
Build 605 outcome was SUCCESS using a merge of d9edd17cfbc8eda00c704e0172b9e76a71646738 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/605
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/605

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
