### PR TITLE
 Add a test for Issue 1834

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 857376fa24b267c1485e1f1e3ccffb01200fc8e9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 393 outcome was FAILURE using a merge of 857376fa24b267c1485e1f1e3ccffb01200fc8e9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/393
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/393

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by weld-tester** [comment]
Build 393 outcome was FAILURE using a merge of 857376fa24b267c1485e1f1e3ccffb01200fc8e9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/393
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/393

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
