### PR TITLE
WELD-1922 Backport SE API enhancements

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 928 is now running using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Build 928 outcome was SUCCESS using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/928
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/928

**Comment by weld-tester** [comment]
Triggering build using a merge of 82d7855a5af88b85bb947cca54c572a21226606d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
