### PR TITLE
WELD-1845 Be tolerant if there is no @Intercepted bean metadata available

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e4f7fe9fc5ea4e1fb403e962845df22b27fb7276 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 443 is now running using a merge of e4f7fe9fc5ea4e1fb403e962845df22b27fb7276 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/443

**Comment by weld-tester** [comment]
Build 443 outcome was SUCCESS using a merge of e4f7fe9fc5ea4e1fb403e962845df22b27fb7276 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/443
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/443

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
