### PR TITLE
Move PropertiesBuilder to tests-common.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 389f137fbdec5e2a94e5e79a87ad935f8290c483 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 658 outcome was FAILURE using a merge of 389f137fbdec5e2a94e5e79a87ad935f8290c483 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/658
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/658

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 389f137fbdec5e2a94e5e79a87ad935f8290c483 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 660 is now running using a merge of 389f137fbdec5e2a94e5e79a87ad935f8290c483 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/660

**Comment by weld-tester** [comment]
Build 660 outcome was SUCCESS using a merge of 389f137fbdec5e2a94e5e79a87ad935f8290c483 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/660
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/660

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
