### PR TITLE
WeldConfiguration - some more comments for impl. details, cleanup

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 1ed8ff0f901c5a6f9e550d4b396561bcc3f8ebb2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 515 is now running using a merge of 1ed8ff0f901c5a6f9e550d4b396561bcc3f8ebb2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/515

**Comment by weld-tester** [comment]
Build 515 outcome was SUCCESS using a merge of 1ed8ff0f901c5a6f9e550d4b396561bcc3f8ebb2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/515
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/515

**Comment by weld-tester** [comment]
Build 515 outcome was SUCCESS using a merge of 1ed8ff0f901c5a6f9e550d4b396561bcc3f8ebb2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/515
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/515

**Comment by weld-tester** [comment]
Build 515 outcome was SUCCESS using a merge of 1ed8ff0f901c5a6f9e550d4b396561bcc3f8ebb2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/515
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/515

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
