### PR TITLE
Probe - various UI improvements

### PR DESCRIPTION
**Pull request by mkouba**
- make invocation tree graph more usable (height is now dynamic)
- add breadcrumbs
- highlight changed values in configuration

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 575 outcome was FAILURE using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/575
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/575

**Comment by weld-tester** [comment]
Build 575 outcome was FAILURE using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/575
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/575

**Comment by weld-tester** [comment]
Build 575 outcome was FAILURE using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/575
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/575

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 577 is now running using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/577

**Comment by weld-tester** [comment]
Build 577 outcome was SUCCESS using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/577
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/577

**Comment by weld-tester** [comment]
Build 577 outcome was SUCCESS using a merge of 74a11eb6d253d7c1d9a5fe670651abfeabddbb95 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/577
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/577

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
