### PR TITLE
One more update of TCK version.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 9f7b2d24c883f21c9ade261c7f97f5fdced98c23 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 904 is now running using a merge of 9f7b2d24c883f21c9ade261c7f97f5fdced98c23 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/904

**Comment by weld-tester** [comment]
Build 904 outcome was SUCCESS using a merge of 9f7b2d24c883f21c9ade261c7f97f5fdced98c23 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/904
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/904

**Comment by weld-tester** [comment]
Build 904 outcome was SUCCESS using a merge of 9f7b2d24c883f21c9ade261c7f97f5fdced98c23 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/904
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/904

**Comment by weld-tester** [comment]
Build 904 outcome was SUCCESS using a merge of 9f7b2d24c883f21c9ade261c7f97f5fdced98c23 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/904
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/904

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
