### PR TITLE
WELD-2061 Probe should be part of the OSGi bundle

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by tremes** [comment]
I am not really sure how I can properly verify our OSGI bundle. Maybe we should think of some reasonable way of verification.

**Comment by mkouba** [comment]
@tremes Running the Weld Paint Example and PAX CDI test suite should be enough.

**Comment by tremes** [comment]
I am not aware of any such testsuite and I think running our example doesn't mean lot wrt verification of bundle itself.

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
