### PR TITLE
WELD-1929 Ref. guide - add some info about logging

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7962a1cc9bcc54d392408ff9316aca5986d09ba4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 766 is now running using a merge of 7962a1cc9bcc54d392408ff9316aca5986d09ba4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/766

**Comment by weld-tester** [comment]
Build 766 outcome was SUCCESS using a merge of 7962a1cc9bcc54d392408ff9316aca5986d09ba4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/766
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/766

**Comment by weld-tester** [comment]
Build 766 outcome was SUCCESS using a merge of 7962a1cc9bcc54d392408ff9316aca5986d09ba4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/766
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/766

**Comment by weld-tester** [comment]
Build 766 outcome was SUCCESS using a merge of 7962a1cc9bcc54d392408ff9316aca5986d09ba4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/766
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/766

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
