### PR TITLE
Weld 1826

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f64c453d82f75379b0894314b00170785a8bef3a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 454 outcome was FAILURE using a merge of f64c453d82f75379b0894314b00170785a8bef3a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/454
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/454

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by weld-tester** [comment]
Triggering build using a merge of 5374300237ddde66b164ec17a7dabf6d58f5c1ae on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 455 is now running using a merge of 5374300237ddde66b164ec17a7dabf6d58f5c1ae on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/455

**Comment by weld-tester** [comment]
Build 455 outcome was FAILURE using a merge of 5374300237ddde66b164ec17a7dabf6d58f5c1ae on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/455
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/455

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 5374300237ddde66b164ec17a7dabf6d58f5c1ae on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 457 is now running using a merge of 5374300237ddde66b164ec17a7dabf6d58f5c1ae on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/457

**Comment by weld-tester** [comment]
Build 457 outcome was SUCCESS using a merge of 5374300237ddde66b164ec17a7dabf6d58f5c1ae on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/457
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/457

**Comment by weld-tester** [comment]
Triggering build using a merge of e19ec2a00cff139a0d5bf840617bdb1ed696abe7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 465 is now running using a merge of e19ec2a00cff139a0d5bf840617bdb1ed696abe7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/465

**Comment by weld-tester** [comment]
Triggering build using a merge of c4e05546d49a8a6889c2c19a9c4595e01a9517fe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 466 is now running using a merge of c4e05546d49a8a6889c2c19a9c4595e01a9517fe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/466

**Comment by weld-tester** [comment]
Build 466 outcome was SUCCESS using a merge of c4e05546d49a8a6889c2c19a9c4595e01a9517fe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/466
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/466

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
