### PR TITLE
Probe - option to specify page size via REST.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 483 is now running using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/483

**Comment by weld-tester** [comment]
Build 483 outcome was SUCCESS using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/483
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/483

**Comment by weld-tester** [comment]
Build 483 outcome was SUCCESS using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/483
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/483

**Comment by weld-tester** [comment]
Build 483 outcome was FAILURE using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/483
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/483

**Comment by weld-tester** [comment]
Build 483 outcome was FAILURE using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/483
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/483

**Comment by weld-tester** [comment]
Build 483 outcome was FAILURE using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/483
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/483

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 489 is now running using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/489

**Comment by weld-tester** [comment]
Build 489 outcome was SUCCESS using a merge of 37ee6b66422970d8532f286eb72bb379a9afcb1a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/489
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/489

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
