### PR TITLE
WELD-1987 Fix format in some log messages

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7568cc5fc08f746decfc9279ca005e6771245496 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 912 is now running using a merge of 7568cc5fc08f746decfc9279ca005e6771245496 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/912

**Comment by weld-tester** [comment]
Build 912 outcome was SUCCESS using a merge of 7568cc5fc08f746decfc9279ca005e6771245496 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/912
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/912

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
