### PR TITLE
Testcase for WELD-1846

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 9b4d02fb68ec5156cdecae4edd28749769a5d19a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by weld-tester** [comment]
Build 459 is now running using a merge of 9b4d02fb68ec5156cdecae4edd28749769a5d19a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/459

**Comment by weld-tester** [comment]
Build 459 outcome was SUCCESS using a merge of 9b4d02fb68ec5156cdecae4edd28749769a5d19a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/459
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/459

**Comment by weld-tester** [comment]
Triggering build using a merge of 39bca5940185615ce10af422346cfc1a6caf1366 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 462 is now running using a merge of 39bca5940185615ce10af422346cfc1a6caf1366 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/462

**Comment by weld-tester** [comment]
Build 462 outcome was SUCCESS using a merge of 39bca5940185615ce10af422346cfc1a6caf1366 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/462
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/462

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
