### PR TITLE
Probe add jacoco profile

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 571 is now running using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/571

**Comment by weld-tester** [comment]
Build 571 outcome was SUCCESS using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/571
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/571

**Comment by weld-tester** [comment]
Build 571 outcome was SUCCESS using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/571
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/571

**Comment by weld-tester** [comment]
Build 571 outcome was SUCCESS using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/571
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/571

**Comment by weld-tester** [comment]
Build 571 outcome was SUCCESS using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/571
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/571

**Comment by weld-tester** [comment]
Build 571 outcome was SUCCESS using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/571
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/571

**Comment by weld-tester** [comment]
Build 571 outcome was SUCCESS using a merge of 8f88fd0a6d1def2e8f5d6a003418c4595f6fad99 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/571
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/571

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
