### PR TITLE
WELD-2113 introduce configuration properties for conversation timeout

### PR DESCRIPTION
**Pull request by tremes**
and conversation conccurent access timeout.

### CODE REVIEW

**Comment by manovotn** [comment]
We might also want to update doc section 5.3.3. Conversation timeout and mention that the timeout is configurable. 
Furthermore somewhere in the doc we should say that this timeout configuration is only a 'hint' for the container as the conversation might get destroyed earlier due to HTTP session invalidation or HTTP session timeout.

**Comment by mkouba** [comment]
@manovotn Good points. Otherwise looks good.

**Comment by tremes** [comment]
Yes I am going to expand `5.3.3. Conversation timeout`. Wrt the second point - we have following (which seems to me sufficient) in `22.1. Managing the built in contexts`:
>The bound session context works in much the same way, excepting that invalidating and deactivating the session context causes the any conversations in the session to be destroyed as well.

Or do you guys have any other suggestions how to improve doc?

**Comment by mkouba** [comment]
@tremes @manovotn I think the regular users usually don't read `Managing the built in contexts` section. I would add this info to `5.3.3. Conversation timeout`.

**Comment by manovotn** [comment]
@mkouba +1

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
