### PR TITLE
WELD-1869 Probe - mention configuration properties in ref guide

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 1d9c19189025e8ab5faec8c3bd2a0ceb7c8bab21 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 506 is now running using a merge of 1d9c19189025e8ab5faec8c3bd2a0ceb7c8bab21 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/506

**Comment by weld-tester** [comment]
Build 506 outcome was SUCCESS using a merge of 1d9c19189025e8ab5faec8c3bd2a0ceb7c8bab21 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/506
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/506

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
