### PR TITLE
WELD-1597 test.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d1cb1b329e38beda8b8b8c080572726f34d82b74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 668 outcome was FAILURE using a merge of d1cb1b329e38beda8b8b8c080572726f34d82b74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/668
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/668

**Comment by jharting** [comment]
If the test is failing currently it needs to be ignored.

**Comment by weld-tester** [comment]
Triggering build using a merge of 5a8c7288d5d8eda2a22479245f28c3f9080eeb02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 669 is now running using a merge of 5a8c7288d5d8eda2a22479245f28c3f9080eeb02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/669

**Comment by weld-tester** [comment]
Build 669 outcome was SUCCESS using a merge of 5a8c7288d5d8eda2a22479245f28c3f9080eeb02 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/669
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/669

**Comment by jharting** [comment]
merged, thanks!

**Pull request closed without merging**
