### PR TITLE
WELD-2639 Allow to expand set of BDA via generic properties.

### PR DESCRIPTION
**Pull request by manovotn**
An impl for WELD-2639. If approved, similar change should go to 3.1 branch.

### CODE REVIEW

**Comment by manovotn** [comment]
TODO - in order to be consistent, we should also add the ability to register this as a system property. E.g. `-Dorg.jboss.weld.se.additionalBeanDefiningAnnotations=org.my.SomeAnnotations,org.another.AnotherAnnotation`

**Comment by manovotn** [comment]
@mkouba how about now?

**Review by mkouba — APPROVED** [review]
Looks great!

**Comment by manovotn** [comment]
Rebased to trigger tests.

**Pull request merged**
