### PR TITLE
WELD-1862 Probe - fix filtering by intercepted bean class

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 17916cab78b5cd3d9b301c08bf02dcf0144984b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 475 is now running using a merge of 17916cab78b5cd3d9b301c08bf02dcf0144984b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/475

**Comment by weld-tester** [comment]
Build 475 outcome was SUCCESS using a merge of 17916cab78b5cd3d9b301c08bf02dcf0144984b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/475
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/475

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
