### PR TITLE
WELD-1975 Allow to use the legacy strategy to infer default bean name

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 873 is now running using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by weld-tester** [comment]
Build 873 outcome was SUCCESS using a merge of 0b425f6c83d2cfff6daa6ac70d042570f6b0d60d on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/873
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/873

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
