### PR TITLE
WELD-1879 Show bean discovery mode for an implicit bean archive without

### PR DESCRIPTION
**Pull request by mkouba**
beans.xml file

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of bc4c994ffc767600e9cf0a23ce659bb3b38f6fbf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 542 is now running using a merge of bc4c994ffc767600e9cf0a23ce659bb3b38f6fbf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/542

**Comment by weld-tester** [comment]
Build 542 outcome was SUCCESS using a merge of bc4c994ffc767600e9cf0a23ce659bb3b38f6fbf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/542
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/542

**Comment by weld-tester** [comment]
Build 542 outcome was SUCCESS using a merge of bc4c994ffc767600e9cf0a23ce659bb3b38f6fbf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/542
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/542

**Comment by weld-tester** [comment]
Build 542 outcome was SUCCESS using a merge of bc4c994ffc767600e9cf0a23ce659bb3b38f6fbf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/542
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/542

**Comment by weld-tester** [comment]
Build 542 outcome was SUCCESS using a merge of bc4c994ffc767600e9cf0a23ce659bb3b38f6fbf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/542
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/542

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
