### PR TITLE
Probe add README file.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f6ba029ba270f25c5a13a753d782da4970c7bf5d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 559 is now running using a merge of f6ba029ba270f25c5a13a753d782da4970c7bf5d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/559

**Comment by weld-tester** [comment]
Triggering build using a merge of 819335f4508ff71091bf3cfc8e3e0905745f41f7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Triggering build using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 561 is now running using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/561

**Comment by weld-tester** [comment]
Build 561 outcome was SUCCESS using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/561
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/561

**Comment by weld-tester** [comment]
Build 561 outcome was SUCCESS using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/561
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/561

**Comment by weld-tester** [comment]
Build 561 outcome was SUCCESS using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/561
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/561

**Comment by weld-tester** [comment]
Build 561 outcome was SUCCESS using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/561
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/561

**Comment by weld-tester** [comment]
Build 561 outcome was SUCCESS using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/561
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/561

**Comment by weld-tester** [comment]
Build 561 outcome was SUCCESS using a merge of c1439c61fae808d6dade7317732572fa150c1277 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/561
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/561

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
