### PR TITLE
Logging - remove all unused messages

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 850 is now running using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/850

**Comment by weld-tester** [comment]
Build 850 outcome was FAILURE using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/850
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/850

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 851 is now running using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/851

**Comment by weld-tester** [comment]
Build 851 outcome was SUCCESS using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/851
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/851

**Comment by weld-tester** [comment]
Build 851 outcome was SUCCESS using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/851
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/851

**Comment by weld-tester** [comment]
Build 851 outcome was SUCCESS using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/851
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/851

**Comment by weld-tester** [comment]
Build 851 outcome was SUCCESS using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/851
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/851

**Comment by weld-tester** [comment]
Build 851 outcome was SUCCESS using a merge of 360c89567085e2fb3e7179907f5226fb1b447576 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/851
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/851

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
