### PR TITLE
Upgrade CDI API to 2.0-EDR1, add stubs to fix compilation problems

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 896 outcome was FAILURE using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/896
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/896

**Comment by weld-tester** [comment]
Build 896 outcome was FAILURE using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/896
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/896

**Comment by weld-tester** [comment]
Build 896 outcome was FAILURE using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/896
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/896

**Comment by weld-tester** [comment]
Build 896 outcome was FAILURE using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/896
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/896

**Comment by weld-tester** [comment]
Build 896 outcome was FAILURE using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/896
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/896

**Comment by weld-tester** [comment]
Build 896 outcome was FAILURE using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/896
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/896

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 900 outcome was FAILURE using a merge of 0683f2447db37b231e11e51e74496568ee28cdd5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/900
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/900

**Pull request closed without merging**
