### PR TITLE
Getting rid auto-generated TODO comments

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 4992f73d937a542e8353be531908651fdf56120b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by weld-tester** [comment]
Build 464 is now running using a merge of 4992f73d937a542e8353be531908651fdf56120b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/464

**Comment by weld-tester** [comment]
Build 464 outcome was SUCCESS using a merge of 4992f73d937a542e8353be531908651fdf56120b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/464
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/464

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
