### PR TITLE
WELD-2672 Make sure proxies for producer always have the package and …

### PR DESCRIPTION
**Pull request by manovotn**
…class of the most specific type we know of.

Also add a test that simulates a situtation similar to the reported problem.

### CODE REVIEW

**Comment by manovotn** [comment]
@beikov if you could confirm that the snapshot from this PR/branch fixes your problem, that would be great :-)

**Comment by beikov** [comment]
Hey @manovotn, thanks for the fix. I just tried it and it works like a charm. Looking forward to use 3.1.8.Final :)

**Comment by manovotn** [comment]
@mkouba could you review this, please?

**Review by mkouba — APPROVED** [review]
Looks good.

**Pull request merged**
