### PR TITLE
WELD-1983 Document defaultNamesFollowJavaBeanRules property

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 6ba1b42a81977a2e44357bb00eacd8a93984be2f on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 913 is now running using a merge of 6ba1b42a81977a2e44357bb00eacd8a93984be2f on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/913

**Comment by weld-tester** [comment]
Build 913 outcome was SUCCESS using a merge of 6ba1b42a81977a2e44357bb00eacd8a93984be2f on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/913
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/913

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
