### PR TITLE
Testing Jenkins pull request integration

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by jharting** [comment]
ok to test

**Comment by weld-tester** [comment]
Triggering build using a merge of 475307b920ab6843e13d4b40db192c0ea20049b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 967 is now running using a merge of 475307b920ab6843e13d4b40db192c0ea20049b0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/967

**Comment by jharting** [comment]
Debugged, thanks :-)

**Pull request closed without merging**
