### PR TITLE
Probe changes

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 66617d251c644138c39ea5140f0a818e3bcd977f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by mkouba** [comment]
Looks good!

**Comment by weld-tester** [comment]
Build 429 is now running using a merge of 66617d251c644138c39ea5140f0a818e3bcd977f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/429

**Comment by weld-tester** [comment]
Build 429 outcome was SUCCESS using a merge of 66617d251c644138c39ea5140f0a818e3bcd977f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/429
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/429

**Pull request merged**
