### PR TITLE
One more update of TCK version.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 1b9aceb0eb791d604cc0203a1c63ea828c4e21b8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 905 is now running using a merge of 1b9aceb0eb791d604cc0203a1c63ea828c4e21b8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/905

**Comment by weld-tester** [comment]
Build 905 outcome was SUCCESS using a merge of 1b9aceb0eb791d604cc0203a1c63ea828c4e21b8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/905
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/905

**Comment by weld-tester** [comment]
Build 905 outcome was SUCCESS using a merge of 1b9aceb0eb791d604cc0203a1c63ea828c4e21b8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/905
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/905

**Comment by weld-tester** [comment]
Build 905 outcome was SUCCESS using a merge of 1b9aceb0eb791d604cc0203a1c63ea828c4e21b8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/905
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/905

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
