### PR TITLE
Upgrade TCK and Arquillian versions.

### PR DESCRIPTION
**Pull request by tremes**
This should go also to 2.2.
Conflicts:
	pom.xml

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of b58c212024d1f6d81391ad99173e5bb75c96b5c9 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Triggering build using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 764 is now running using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/764

**Comment by weld-tester** [comment]
Build 764 outcome was FAILURE using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/764
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/764

**Comment by mkouba** [comment]
WELD-1941 was not backported into 2.2 yet. See also https://issues.jboss.org/browse/WELD-1951

**Comment by weld-tester** [comment]
Build 764 outcome was FAILURE using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/764
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/764

**Comment by weld-tester** [comment]
Build 764 outcome was FAILURE using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/764
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/764

**Comment by weld-tester** [comment]
Build 764 outcome was FAILURE using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/764
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/764

**Comment by weld-tester** [comment]
Build 764 outcome was FAILURE using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/764
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/764

**Comment by weld-tester** [comment]
Build 764 outcome was FAILURE using a merge of 6388fcbaaa83aee5d1172ee4544f41ac10f8458a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/764
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/764

**Pull request closed without merging**
