### PR TITLE
WELD-1931 Improve the performance of context activation

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 03cef94efd49f85e1fc7e7e7b2dd788ac206907a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 818 is now running using a merge of 03cef94efd49f85e1fc7e7e7b2dd788ac206907a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/818

**Comment by weld-tester** [comment]
Build 818 outcome was SUCCESS using a merge of 03cef94efd49f85e1fc7e7e7b2dd788ac206907a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/818
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/818

**Comment by weld-tester** [comment]
Build 818 outcome was SUCCESS using a merge of 03cef94efd49f85e1fc7e7e7b2dd788ac206907a on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/818
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/818

**Comment by jharting** [comment]
This PR does not seem to compile on Java 7 (Iterator's remove method was made default in Java 8)

**Comment by weld-tester** [comment]
Triggering build using a merge of 228c728732a5a7dbc11d3c6768864547f02f07a5 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 822 is now running using a merge of 228c728732a5a7dbc11d3c6768864547f02f07a5 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/822

**Comment by weld-tester** [comment]
Build 822 outcome was SUCCESS using a merge of 228c728732a5a7dbc11d3c6768864547f02f07a5 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/822
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/822

**Pull request closed without merging**
