### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 187416fcd4788cf696db6ff96173e9178e29b85e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 447 outcome was FAILURE using a merge of 187416fcd4788cf696db6ff96173e9178e29b85e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/447
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/447

**Comment by weld-tester** [comment]
Triggering build using a merge of f2f6477bf67ac74c8cbe097e28783a40129fc389 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 449 outcome was FAILURE using a merge of f2f6477bf67ac74c8cbe097e28783a40129fc389 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/449
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/449

**Comment by weld-tester** [comment]
Triggering build using a merge of 3153438678a85829698c64dccb29d0bfff6276e4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 451 is now running using a merge of 3153438678a85829698c64dccb29d0bfff6276e4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/451

**Comment by weld-tester** [comment]
Build 451 outcome was SUCCESS using a merge of 3153438678a85829698c64dccb29d0bfff6276e4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/451
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/451

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
