### PR TITLE
Mention Probe in the reference documentation

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 2d60dac370c3854945a1efbf4b160ffef1170b26 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 453 is now running using a merge of 2d60dac370c3854945a1efbf4b160ffef1170b26 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/453

**Comment by weld-tester** [comment]
Build 453 outcome was SUCCESS using a merge of 2d60dac370c3854945a1efbf4b160ffef1170b26 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/453
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/453

**Comment by mkouba** [comment]
Unfortunately, it's not possible to easily export JS editor formatter settings in Eclipse IDE.

**Comment by weld-tester** [comment]
Triggering build using a merge of 8dd6895b191066caff4d86b09da8b3b823bf9cfe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 458 is now running using a merge of 8dd6895b191066caff4d86b09da8b3b823bf9cfe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/458

**Comment by weld-tester** [comment]
Build 458 outcome was SUCCESS using a merge of 8dd6895b191066caff4d86b09da8b3b823bf9cfe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/458
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/458

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
