### PR TITLE
WELD-1959 Fix Jetty container detection

### PR DESCRIPTION
**Pull request by mkouba**
- also upgrade test versions of Tomcat and Jetty

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 3cde801cbc7a187b2766dc3404520a3a31dae994 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 782 is now running using a merge of 3cde801cbc7a187b2766dc3404520a3a31dae994 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/782

**Comment by weld-tester** [comment]
Build 782 outcome was SUCCESS using a merge of 3cde801cbc7a187b2766dc3404520a3a31dae994 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/782
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/782

**Comment by weld-tester** [comment]
Build 782 outcome was SUCCESS using a merge of 3cde801cbc7a187b2766dc3404520a3a31dae994 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/782
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/782

**Comment by mkouba** [comment]
Closing in favor of https://github.com/weld/core/pull/991

**Pull request closed without merging**
