### PR TITLE
Probe - improvements 3

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 84881f3b89e5df7f84481c28ef0f3de77e21ac72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 448 is now running using a merge of 84881f3b89e5df7f84481c28ef0f3de77e21ac72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/448

**Comment by weld-tester** [comment]
Build 448 outcome was SUCCESS using a merge of 84881f3b89e5df7f84481c28ef0f3de77e21ac72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/448
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/448

**Comment by weld-tester** [comment]
Triggering build using a merge of da0385a361876d92c0a5464fddccaaff6e03ae7c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 450 is now running using a merge of da0385a361876d92c0a5464fddccaaff6e03ae7c on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/450

**Comment by weld-tester** [comment]
Triggering build using a merge of 90538d8f7633dac3efc8d7171e5b3581c64713d6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 452 is now running using a merge of 90538d8f7633dac3efc8d7171e5b3581c64713d6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/452

**Comment by weld-tester** [comment]
Build 452 outcome was SUCCESS using a merge of 90538d8f7633dac3efc8d7171e5b3581c64713d6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/452
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/452

**Comment by weld-tester** [comment]
Build 452 outcome was SUCCESS using a merge of 90538d8f7633dac3efc8d7171e5b3581c64713d6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/452
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/452

**Comment by weld-tester** [comment]
Build 452 outcome was SUCCESS using a merge of 90538d8f7633dac3efc8d7171e5b3581c64713d6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/452
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/452

**Comment by weld-tester** [comment]
Build 452 outcome was SUCCESS using a merge of 90538d8f7633dac3efc8d7171e5b3581c64713d6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/452
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/452

**Comment by weld-tester** [comment]
Build 452 outcome was SUCCESS using a merge of 90538d8f7633dac3efc8d7171e5b3581c64713d6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/452
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/452

**Comment by jharting** [comment]
Very nice! Merged.

**Pull request closed without merging**
