### PR TITLE
Built-in bean ID should contain AbstractBuiltInBean instead of AbstractSyntheticBean

### PR DESCRIPTION
**Pull request by mkouba**
Should be applied to 2.2 as well.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 4aba1d9c4849ae16c0a45ef2eb65bac3e4ddcf72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 720 is now running using a merge of 4aba1d9c4849ae16c0a45ef2eb65bac3e4ddcf72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/720

**Comment by weld-tester** [comment]
Build 720 outcome was SUCCESS using a merge of 4aba1d9c4849ae16c0a45ef2eb65bac3e4ddcf72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/720
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/720

**Comment by weld-tester** [comment]
Build 720 outcome was SUCCESS using a merge of 4aba1d9c4849ae16c0a45ef2eb65bac3e4ddcf72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/720
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/720

**Comment by weld-tester** [comment]
Build 720 outcome was SUCCESS using a merge of 4aba1d9c4849ae16c0a45ef2eb65bac3e4ddcf72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/720
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/720

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
