### PR TITLE
Upgrade WF9 Arquillian adapter to 1.0.0.Alpha2

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 610 is now running using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/610

**Comment by weld-tester** [comment]
Build 610 outcome was FAILURE using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/610
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/610

**Comment by jharting** [comment]
Waiting for probe integration tests to support WF9

**Comment by weld-tester** [comment]
Build 610 outcome was FAILURE using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/610
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/610

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 618 is now running using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/618

**Comment by weld-tester** [comment]
Build 618 outcome was SUCCESS using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/618
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/618

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 619 is now running using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/619

**Comment by weld-tester** [comment]
Build 619 outcome was FAILURE using a merge of 7e34e8603991e13378f6db4177cc0315bd65d5c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/619
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/619

**Comment by weld-tester** [comment]
Triggering build using a merge of 22b1197b7742fb06cdaea6f1e7c2a0c7997a3e93 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Triggering build using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 622 outcome was FAILURE using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/622
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/622

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 623 is now running using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/623

**Comment by weld-tester** [comment]
Build 623 outcome was FAILURE using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/623
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/623

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 626 is now running using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/626

**Comment by weld-tester** [comment]
Build 626 outcome was FAILURE using a merge of 2d02f3bfd7212c66842e21c2e47cb36dba110c2b on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/626
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/626

**Comment by weld-tester** [comment]
Triggering build using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 627 is now running using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/627

**Comment by weld-tester** [comment]
Build 627 outcome was FAILURE using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/627
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/627

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 628 is now running using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/628

**Comment by weld-tester** [comment]
Build 628 outcome was FAILURE using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/628
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/628

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 629 is now running using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/629

**Comment by weld-tester** [comment]
Build 629 outcome was FAILURE using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/629
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/629

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 631 is now running using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/631

**Comment by weld-tester** [comment]
Build 631 outcome was SUCCESS using a merge of 6d7c1c75f01b574d39f02f63777b6f264a416fe6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/631
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/631

**Pull request closed without merging**
