### PR TITLE
Close code snippet to fix next chapters

### PR DESCRIPTION
**Pull request by hasys**
See here: http://docs.jboss.org/weld/reference/latest-master/en-US/html/

After chapter `9. Interceptors` following chapter `10. public void afterPersonalBlogUpdate(@Observes @Updated @Personal @Blog Document document) { … }`, but should be `10. Decorators`. It is caused by unclosed source tag in Interceptors chapter.

### CODE REVIEW

**Comment by manovotn** [comment]
test this please

**Comment by manovotn** [comment]
@hasys nice catch, thanks you!
I can see we are having the same glitch in 2.4 branch

**Comment by mkouba** [comment]
Thanks Kirill and welcome back to the team of Weld contributors ;-)

**Comment by hasys** [comment]
Hi @mkouba, 
thank you it is nice to be useful again :)

Thank you @manovotn, I created separate PR for 2.4 branch. See here: https://github.com/weld/core/pull/1794

**Pull request merged**
