### PR TITLE
WFLY-4438 Only test that constructor is not called per method invocation

### PR DESCRIPTION
**Pull request by mkouba**
See also https://github.com/wildfly/wildfly/pull/7277

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 594 is now running using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/594

**Comment by weld-tester** [comment]
Build 594 outcome was SUCCESS using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/594
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/594

**Comment by weld-tester** [comment]
Build 594 outcome was SUCCESS using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/594
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/594

**Comment by weld-tester** [comment]
Build 594 outcome was SUCCESS using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/594
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/594

**Comment by weld-tester** [comment]
Build 594 outcome was SUCCESS using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/594
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/594

**Comment by jharting** [comment]
retest this please (with WF9)

**Comment by weld-tester** [comment]
Triggering build using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 609 is now running using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/609

**Comment by weld-tester** [comment]
Build 609 outcome was FAILURE using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/609
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/609

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 612 is now running using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/612

**Comment by weld-tester** [comment]
Build 612 outcome was SUCCESS using a merge of 0b6129c40a13f1298a7e4e7fdc760b099a764406 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/612
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/612

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
