### PR TITLE
WELD-1857, WELD-1858 Weld OSGi bundle

### PR DESCRIPTION
**Pull request by mkouba**
- export org.jboss.weld.security package
- declare correct Specification-Version

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7b29f9b7e8c61bc28a3b71b18c8526ac653082b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 471 is now running using a merge of 7b29f9b7e8c61bc28a3b71b18c8526ac653082b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/471

**Comment by weld-tester** [comment]
Build 471 outcome was SUCCESS using a merge of 7b29f9b7e8c61bc28a3b71b18c8526ac653082b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/471
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/471

**Comment by weld-tester** [comment]
Build 471 outcome was SUCCESS using a merge of 7b29f9b7e8c61bc28a3b71b18c8526ac653082b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/471
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/471

**Comment by weld-tester** [comment]
Build 471 outcome was SUCCESS using a merge of 7b29f9b7e8c61bc28a3b71b18c8526ac653082b9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/471
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/471

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
