### PR TITLE
WELD-1818 Detect bean identifier index inconsistency

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of cf917942a014a9363072f3ddc550146021275215 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 403 is now running using a merge of cf917942a014a9363072f3ddc550146021275215 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/403

**Comment by weld-tester** [comment]
Build 403 outcome was SUCCESS using a merge of cf917942a014a9363072f3ddc550146021275215 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/403
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/403

**Comment by weld-tester** [comment]
Build 403 outcome was SUCCESS using a merge of cf917942a014a9363072f3ddc550146021275215 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/403
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/403

**Comment by weld-tester** [comment]
Build 403 outcome was SUCCESS using a merge of cf917942a014a9363072f3ddc550146021275215 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/403
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/403

**Comment by weld-tester** [comment]
Build 403 outcome was SUCCESS using a merge of cf917942a014a9363072f3ddc550146021275215 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/403
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/403

**Comment by weld-tester** [comment]
Build 403 outcome was SUCCESS using a merge of cf917942a014a9363072f3ddc550146021275215 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/403
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/403

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
