### PR TITLE
WELD-1933 Add profile to activate weld-logging-tools annotation proce…

### PR DESCRIPTION
**Pull request by mkouba**
…ssor

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7adca2399e275bffd60068dbb617653afda47046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 752 is now running using a merge of 7adca2399e275bffd60068dbb617653afda47046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/752

**Comment by weld-tester** [comment]
Build 752 outcome was SUCCESS using a merge of 7adca2399e275bffd60068dbb617653afda47046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/752
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/752

**Comment by weld-tester** [comment]
Build 752 outcome was SUCCESS using a merge of 7adca2399e275bffd60068dbb617653afda47046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/752
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/752

**Comment by weld-tester** [comment]
Build 752 outcome was SUCCESS using a merge of 7adca2399e275bffd60068dbb617653afda47046 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/752
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/752

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
