### PR TITLE
WELD-1868 Allow to search the whole invocation trees

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 98559f7e907cd7ce9a8cf1e4a90b14579bf561a6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 484 is now running using a merge of 98559f7e907cd7ce9a8cf1e4a90b14579bf561a6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/484

**Comment by weld-tester** [comment]
Build 484 outcome was ABORTED using a merge of 98559f7e907cd7ce9a8cf1e4a90b14579bf561a6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/484
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/484

**Comment by weld-tester** [comment]
Build 484 outcome was ABORTED using a merge of 98559f7e907cd7ce9a8cf1e4a90b14579bf561a6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/484
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/484

**Comment by weld-tester** [comment]
Build 484 outcome was ABORTED using a merge of 98559f7e907cd7ce9a8cf1e4a90b14579bf561a6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/484
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/484

**Comment by weld-tester** [comment]
Build 484 outcome was ABORTED using a merge of 98559f7e907cd7ce9a8cf1e4a90b14579bf561a6 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/484
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/484

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
