### PR TITLE
WELD-1949 Log a correct version when used in a fat jar

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of deb876f777f89ea51c5f8f0e5deff3a54bc708b5 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 868 is now running using a merge of deb876f777f89ea51c5f8f0e5deff3a54bc708b5 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/868

**Comment by weld-tester** [comment]
Build 868 outcome was SUCCESS using a merge of deb876f777f89ea51c5f8f0e5deff3a54bc708b5 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/868
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/868

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
