### PR TITLE
WELD-1823 Ensure that there is no injection point associated during

### PR DESCRIPTION
**Pull request by mkouba**
invocation of BeanManager.getReference()

`org.jboss.weld.tests.injectionPoint.weld1823.Weld1823Test` should be revised (see also my comments for https://github.com/weld/core/pull/803).

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 1291d518ce27343c9d6dadc057669dbc5990e611 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 402 is now running using a merge of 1291d518ce27343c9d6dadc057669dbc5990e611 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/402

**Comment by weld-tester** [comment]
Build 402 outcome was SUCCESS using a merge of 1291d518ce27343c9d6dadc057669dbc5990e611 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/402
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/402

**Comment by weld-tester** [comment]
Build 402 outcome was SUCCESS using a merge of 1291d518ce27343c9d6dadc057669dbc5990e611 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/402
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/402

**Comment by weld-tester** [comment]
Build 402 outcome was SUCCESS using a merge of 1291d518ce27343c9d6dadc057669dbc5990e611 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/402
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/402

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
