### PR TITLE
 WELD-1863, WELD-1864, WELD-1865 and minor improvement

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 551cede49d695b1b1f0d3db6211eb27e0ed5d6de on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 477 is now running using a merge of 551cede49d695b1b1f0d3db6211eb27e0ed5d6de on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/477

**Comment by weld-tester** [comment]
Build 477 outcome was SUCCESS using a merge of 551cede49d695b1b1f0d3db6211eb27e0ed5d6de on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/477
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/477

**Comment by weld-tester** [comment]
Build 477 outcome was SUCCESS using a merge of 551cede49d695b1b1f0d3db6211eb27e0ed5d6de on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/477
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/477

**Comment by weld-tester** [comment]
Build 477 outcome was SUCCESS using a merge of 551cede49d695b1b1f0d3db6211eb27e0ed5d6de on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/477
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/477

**Comment by weld-tester** [comment]
Triggering build using a merge of 6e5d990ca3452bdbac65093acac34205386907b3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 478 outcome was FAILURE using a merge of 6e5d990ca3452bdbac65093acac34205386907b3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/478
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/478

**Comment by weld-tester** [comment]
Triggering build using a merge of 6a525d43579a2f18264f80529790eed4c6c74602 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 479 outcome was FAILURE using a merge of 6a525d43579a2f18264f80529790eed4c6c74602 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/479
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/479

**Comment by mkouba** [comment]
The test failure (FireAsyncWithExecutorTest) doesn't seem to be related.

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 6a525d43579a2f18264f80529790eed4c6c74602 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 480 is now running using a merge of 6a525d43579a2f18264f80529790eed4c6c74602 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/480

**Comment by weld-tester** [comment]
Build 480 outcome was SUCCESS using a merge of 6a525d43579a2f18264f80529790eed4c6c74602 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/480
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/480

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
