### PR TITLE
Testcase for giving a priority for the alternative stereotype at runtime

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by weld-tester** [comment]
Triggering build using a merge of a16475a2a00c33be69a27bf7450082b7879c7a37 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 472 is now running using a merge of a16475a2a00c33be69a27bf7450082b7879c7a37 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/472

**Comment by weld-tester** [comment]
Build 472 outcome was SUCCESS using a merge of a16475a2a00c33be69a27bf7450082b7879c7a37 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/472
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/472

**Comment by weld-tester** [comment]
Triggering build using a merge of 3c5a69bb5de7dfdabedd414e0eed559f19b9cd4d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 473 is now running using a merge of 3c5a69bb5de7dfdabedd414e0eed559f19b9cd4d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/473

**Comment by weld-tester** [comment]
Build 473 outcome was SUCCESS using a merge of 3c5a69bb5de7dfdabedd414e0eed559f19b9cd4d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/473
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/473

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
