### PR TITLE
WELD-1880

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of eabc6056655796bd764d10c12679ec8fb27757ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 565 is now running using a merge of eabc6056655796bd764d10c12679ec8fb27757ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/565

**Comment by weld-tester** [comment]
Build 565 outcome was FAILURE using a merge of eabc6056655796bd764d10c12679ec8fb27757ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/565
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/565

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of eabc6056655796bd764d10c12679ec8fb27757ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 568 is now running using a merge of eabc6056655796bd764d10c12679ec8fb27757ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/568

**Comment by weld-tester** [comment]
Build 568 outcome was SUCCESS using a merge of eabc6056655796bd764d10c12679ec8fb27757ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/568
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/568

**Comment by weld-tester** [comment]
Build 568 outcome was SUCCESS using a merge of eabc6056655796bd764d10c12679ec8fb27757ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/568
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/568

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
