### PR TITLE
Getting rid outdated @Ignore annotations

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 4689c2deaf87ac56948cea9766e11a15cef704cc on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Triggering build using a merge of 8258741cb636e215e13dd4d9c07f901e81ffddb7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 405 is now running using a merge of 8258741cb636e215e13dd4d9c07f901e81ffddb7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/405

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by weld-tester** [comment]
Build 405 outcome was SUCCESS using a merge of 8258741cb636e215e13dd4d9c07f901e81ffddb7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/405
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/405

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
