### PR TITLE
WELD-1917 Add test for Weld SE

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of dc870a2d8584537a908690982118e618d88f9584 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 696 is now running using a merge of dc870a2d8584537a908690982118e618d88f9584 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/696

**Comment by weld-tester** [comment]
Build 696 outcome was FAILURE using a merge of dc870a2d8584537a908690982118e618d88f9584 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/696
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/696

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of dc870a2d8584537a908690982118e618d88f9584 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 697 is now running using a merge of dc870a2d8584537a908690982118e618d88f9584 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/697

**Comment by weld-tester** [comment]
Build 697 outcome was SUCCESS using a merge of dc870a2d8584537a908690982118e618d88f9584 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/697
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/697

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
