### PR TITLE
WELD-1875 Probe - beans list improvements

### PR DESCRIPTION
**Pull request by mkouba**
- label selected alternatives (client)
- add isAlternative to filters (API)
- add stereotypes to filters (API)
- treat page <= 0 correctly (API)

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of b65f37168c261fd6b060b85efde808da9cd2f00e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 528 is now running using a merge of b65f37168c261fd6b060b85efde808da9cd2f00e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/528

**Comment by weld-tester** [comment]
Build 528 outcome was SUCCESS using a merge of b65f37168c261fd6b060b85efde808da9cd2f00e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/528
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/528

**Comment by weld-tester** [comment]
Build 528 outcome was SUCCESS using a merge of b65f37168c261fd6b060b85efde808da9cd2f00e on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/528
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/528

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
