### PR TITLE
WELD-2499 Add BCEL as option import into OSGi.

### PR DESCRIPTION
**Pull request by manovotn**

### CODE REVIEW

**Comment by manovotn** [comment]
retest this please

**Comment by manovotn** [comment]
test with GF

**Comment by manovotn** [comment]
test with GF

**Comment by manovotn** [comment]
test with GF

**Comment by manovotn** [comment]
test with GF

**Comment by manovotn** [comment]
test with GF

**Comment by mkouba** [comment]
@manovotn Can I merge this one?

**Comment by manovotn** [comment]
@mkouba yes, all CI jobs are green

**Pull request merged**
