### PR TITLE
Increase container connection timeout for SE tests. Windows machines …

### PR DESCRIPTION
**Pull request by manovotn**
…were failing.

I came across a (random) timeout on Win machine during release testing. I think it will do no harm to increase the timeout here.

### CODE REVIEW

**Comment by tremes** [comment]
I would rather introduce configurable variable so that you can pass value only for related jobs.

**Comment by manovotn** [comment]
Hmm, that's also an option, but that would require modifications to jenkins job. I mean add OS specific bash code. While it's easy to do, I don't like that approach for maintenance.
Extending total time doesn't necessarily mean the jobs will take longer, only that it will wait if need be. What is it you don't like about it?

**Comment by mkouba** [comment]
I think it's fine to use the increased hardcoded value here.

**Comment by tremes** [comment]
I am not saying I don't like it. I just think the variable is more universal solution. What if 25 is still not enough?

**Comment by mkouba** [comment]
@tremes @manovotn `arquillian.xml` does support properties with default values, or?

**Comment by tremes** [comment]
Yes I think so. We have something like that in `jboss-tck-runner/src/test/wildfly8/arquillian.xml`

**Comment by mkouba** [comment]
+1 Yep, that's the way to go. I think.

**Comment by manovotn** [comment]
Didn't know it supports default. Fair enough then, I will change it to variable.

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
