### PR TITLE
Probe - fix and improvements

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of c8e9623213ee6fddbe8002976ecc5d895a005206 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 467 is now running using a merge of c8e9623213ee6fddbe8002976ecc5d895a005206 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/467

**Comment by weld-tester** [comment]
Build 467 outcome was SUCCESS using a merge of c8e9623213ee6fddbe8002976ecc5d895a005206 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/467
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/467

**Comment by weld-tester** [comment]
Build 467 outcome was SUCCESS using a merge of c8e9623213ee6fddbe8002976ecc5d895a005206 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/467
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/467

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
