### PR TITLE
Upgrade TCK version.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 3ced9512a0f8e4b1831bb54d7272c162e3d885bd on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 759 is now running using a merge of 3ced9512a0f8e4b1831bb54d7272c162e3d885bd on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/759

**Comment by weld-tester** [comment]
Build 759 outcome was SUCCESS using a merge of 3ced9512a0f8e4b1831bb54d7272c162e3d885bd on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/759
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/759

**Comment by weld-tester** [comment]
Triggering build using a merge of cddccc799751e72608f1554b63d19892c991e466 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 760 is now running using a merge of cddccc799751e72608f1554b63d19892c991e466 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/760

**Comment by weld-tester** [comment]
Build 760 outcome was SUCCESS using a merge of cddccc799751e72608f1554b63d19892c991e466 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/760
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/760

**Comment by weld-tester** [comment]
Build 760 outcome was SUCCESS using a merge of cddccc799751e72608f1554b63d19892c991e466 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/760
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/760

**Comment by weld-tester** [comment]
Build 760 outcome was SUCCESS using a merge of cddccc799751e72608f1554b63d19892c991e466 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/760
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/760

**Comment by weld-tester** [comment]
Build 760 outcome was SUCCESS using a merge of cddccc799751e72608f1554b63d19892c991e466 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/760
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/760

**Comment by weld-tester** [comment]
Build 760 outcome was SUCCESS using a merge of cddccc799751e72608f1554b63d19892c991e466 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/760
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/760

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
