### PR TITLE
WELD-1956 Make it possible to pass a ClassLoader to be used for scanning in SE

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 829 is now running using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Build 829 outcome was SUCCESS using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Build 829 outcome was SUCCESS using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Build 829 outcome was SUCCESS using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Build 829 outcome was SUCCESS using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Build 829 outcome was SUCCESS using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Build 829 outcome was SUCCESS using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Build 829 outcome was SUCCESS using a merge of 472864cf8920a04c8490e3dc86f4682c6d358f0f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/829
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/829

**Comment by weld-tester** [comment]
Triggering build using a merge of 991601f206f7a396c3ad1e7e17886e42f2e9fe5f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 843 is now running using a merge of 991601f206f7a396c3ad1e7e17886e42f2e9fe5f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/843

**Comment by weld-tester** [comment]
Build 843 outcome was FAILURE using a merge of 991601f206f7a396c3ad1e7e17886e42f2e9fe5f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/843
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/843

**Comment by weld-tester** [comment]
Build 843 outcome was FAILURE using a merge of 991601f206f7a396c3ad1e7e17886e42f2e9fe5f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/843
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/843

**Comment by weld-tester** [comment]
Triggering build using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by weld-tester** [comment]
Build 845 outcome was FAILURE using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/845
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/845

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 853 outcome was SUCCESS using a merge of 14231790ff1dd6d5a8aebe44cd631fedfb9e591f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/853
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/853

**Pull request closed without merging**
