### PR TITLE
WELD-1947 Probe refactoring (simplify integration)

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7b4d778dde9419f7da0648e248be0a835cf8689d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 773 outcome was FAILURE using a merge of 7b4d778dde9419f7da0648e248be0a835cf8689d on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/773
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/773

**Comment by mkouba** [comment]
Production "mode" does not work at the moment...

**Comment by jharting** [comment]
The PR looks good to me :-)

**Comment by weld-tester** [comment]
Triggering build using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by mkouba** [comment]
Both dev and prod mode should work now.

**Comment by weld-tester** [comment]
Build 775 outcome was FAILURE using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/775
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/775

**Comment by weld-tester** [comment]
Build 775 outcome was FAILURE using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/775
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/775

**Comment by mkouba** [comment]
Probe integration tests should pass as soon as https://github.com/weld/wildfly/pull/8 is merged.

**Comment by weld-tester** [comment]
Build 775 outcome was FAILURE using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/775
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/775

**Comment by weld-tester** [comment]
Build 775 outcome was FAILURE using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/775
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/775

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 778 is now running using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/778

**Comment by weld-tester** [comment]
Build 778 outcome was SUCCESS using a merge of c58d1651c6e352ba3a98b8645578bad040799e29 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/778
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/778

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
