### PR TITLE
Upgrade TCK and Arquillian version.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 3f40757df791884491e7988433241981a8524c03 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 806 is now running using a merge of 3f40757df791884491e7988433241981a8524c03 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/806

**Comment by weld-tester** [comment]
Build 806 outcome was FAILURE using a merge of 3f40757df791884491e7988433241981a8524c03 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/806
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/806

**Comment by weld-tester** [comment]
Build 806 outcome was FAILURE using a merge of 3f40757df791884491e7988433241981a8524c03 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/806
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/806

**Comment by weld-tester** [comment]
Build 806 outcome was FAILURE using a merge of 3f40757df791884491e7988433241981a8524c03 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/806
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/806

**Comment by weld-tester** [comment]
Build 806 outcome was FAILURE using a merge of 3f40757df791884491e7988433241981a8524c03 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/806
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/806

**Comment by jharting** [comment]
Do not forget to add an exclusion for WELD-1941 to the exclude list. I am not planning on resolving the issue in 2.2 just yet.

**Comment by tremes** [comment]
Ok I hoped for backport.:)

**Comment by weld-tester** [comment]
Triggering build using a merge of 262172d7f243a52eae7b33b80e9d5e86adf7ad54 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 814 is now running using a merge of 262172d7f243a52eae7b33b80e9d5e86adf7ad54 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/814

**Comment by weld-tester** [comment]
Build 814 outcome was FAILURE using a merge of 262172d7f243a52eae7b33b80e9d5e86adf7ad54 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/814
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/814

**Comment by weld-tester** [comment]
Build 814 outcome was FAILURE using a merge of 262172d7f243a52eae7b33b80e9d5e86adf7ad54 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/814
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/814

**Comment by weld-tester** [comment]
Triggering build using a merge of 58fab6701d36a41eea1f0fc6a22a25aaec58399b on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 817 is now running using a merge of 58fab6701d36a41eea1f0fc6a22a25aaec58399b on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/817

**Comment by weld-tester** [comment]
Triggering build using a merge of 3b69d839616b26b000eb0fccb39b21fd7c375a6e on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 819 is now running using a merge of 3b69d839616b26b000eb0fccb39b21fd7c375a6e on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/819

**Comment by weld-tester** [comment]
Build 819 outcome was SUCCESS using a merge of 3b69d839616b26b000eb0fccb39b21fd7c375a6e on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/819
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/819

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
