### PR TITLE
WELD-1852 Fix invalid warning

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 622db566275040ee55c3f981a2e4480e93c0f6f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 461 is now running using a merge of 622db566275040ee55c3f981a2e4480e93c0f6f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/461

**Comment by weld-tester** [comment]
Build 461 outcome was SUCCESS using a merge of 622db566275040ee55c3f981a2e4480e93c0f6f5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/461
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/461

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
