### PR TITLE
Weld SE, Servlet - set bean deployment archives accessibility clearly

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 6d85fb1772a85f2199880ab2a8b4f02252538a74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 710 is now running using a merge of 6d85fb1772a85f2199880ab2a8b4f02252538a74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/710

**Comment by weld-tester** [comment]
Build 710 outcome was SUCCESS using a merge of 6d85fb1772a85f2199880ab2a8b4f02252538a74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/710
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/710

**Comment by weld-tester** [comment]
Build 710 outcome was SUCCESS using a merge of 6d85fb1772a85f2199880ab2a8b4f02252538a74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/710
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/710

**Comment by weld-tester** [comment]
Build 710 outcome was SUCCESS using a merge of 6d85fb1772a85f2199880ab2a8b4f02252538a74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/710
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/710

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
