### PR TITLE
WELD-1836 TestCase for calling getInjectableReference() with InjectionPo...

### PR DESCRIPTION
**Pull request by Hasys**
...int wich can be used as a source of types and qualifiers only

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f399159408747a518811e337acff46aa111fa2ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 418 is now running using a merge of f399159408747a518811e337acff46aa111fa2ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/418

**Comment by weld-tester** [comment]
Build 418 outcome was FAILURE using a merge of f399159408747a518811e337acff46aa111fa2ac on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/418
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/418

**Comment by weld-tester** [comment]
Triggering build using a merge of f822a76b489c9507ada0f13f11bd9289c2d8ea03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 419 is now running using a merge of f822a76b489c9507ada0f13f11bd9289c2d8ea03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/419

**Comment by weld-tester** [comment]
Build 419 outcome was SUCCESS using a merge of f822a76b489c9507ada0f13f11bd9289c2d8ea03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/419
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/419

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
