### PR TITLE
WELD-2002 Switch to jboss.org templates for reference documentation

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 30a16db82331ec099051c3ccc0a064c0e6bbc4b7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 956 is now running using a merge of 30a16db82331ec099051c3ccc0a064c0e6bbc4b7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/956

**Comment by weld-tester** [comment]
Build 956 outcome was SUCCESS using a merge of 30a16db82331ec099051c3ccc0a064c0e6bbc4b7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/956
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/956

**Comment by weld-tester** [comment]
Build 956 outcome was SUCCESS using a merge of 30a16db82331ec099051c3ccc0a064c0e6bbc4b7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/956
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/956

**Comment by weld-tester** [comment]
Build 956 outcome was SUCCESS using a merge of 30a16db82331ec099051c3ccc0a064c0e6bbc4b7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/956
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/956

**Comment by weld-tester** [comment]
Build 956 outcome was SUCCESS using a merge of 30a16db82331ec099051c3ccc0a064c0e6bbc4b7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/956
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/956

**Comment by weld-tester** [comment]
Build 956 outcome was SUCCESS using a merge of 30a16db82331ec099051c3ccc0a064c0e6bbc4b7 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/956
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/956

**Comment by jharting** [comment]
On hold - pending template modifications (bigger font size, wider paragraphs in the HTML version).

**Comment by jharting** [comment]
Superseded by https://github.com/weld/core/pull/1099

**Pull request closed without merging**
