### PR TITLE
Change javadoc to regular java comments in package-info.java files

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 87e7b91640d83b4ca4949ae1d66ff8a5d29fa1c1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 533 is now running using a merge of 87e7b91640d83b4ca4949ae1d66ff8a5d29fa1c1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/533

**Comment by weld-tester** [comment]
Build 533 outcome was SUCCESS using a merge of 87e7b91640d83b4ca4949ae1d66ff8a5d29fa1c1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/533
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/533

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
