### PR TITLE
WELD-1882 Probe - allow to select/deselect bdas shown in graph

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of fe0907ba33a10a2c4312802c6ae3270b7c288384 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 541 is now running using a merge of fe0907ba33a10a2c4312802c6ae3270b7c288384 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/541

**Comment by weld-tester** [comment]
Build 541 outcome was SUCCESS using a merge of fe0907ba33a10a2c4312802c6ae3270b7c288384 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/541
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/541

**Comment by weld-tester** [comment]
Build 541 outcome was SUCCESS using a merge of fe0907ba33a10a2c4312802c6ae3270b7c288384 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/541
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/541

**Comment by weld-tester** [comment]
Build 541 outcome was SUCCESS using a merge of fe0907ba33a10a2c4312802c6ae3270b7c288384 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/541
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/541

**Comment by weld-tester** [comment]
Build 541 outcome was SUCCESS using a merge of fe0907ba33a10a2c4312802c6ae3270b7c288384 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/541
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/541

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
