### PR TITLE
Testcase for WELD-1846

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 90008a4194e9c1a5032afa10ef3368ff1e2d08dd on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 463 is now running using a merge of 90008a4194e9c1a5032afa10ef3368ff1e2d08dd on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/463

**Comment by weld-tester** [comment]
Build 463 outcome was SUCCESS using a merge of 90008a4194e9c1a5032afa10ef3368ff1e2d08dd on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/463
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/463

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
