### PR TITLE
WELD-1871 Last part

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 512dc890a84bda1cd83e0242950e8fcec3bed299 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 944 is now running using a merge of 512dc890a84bda1cd83e0242950e8fcec3bed299 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/944

**Comment by weld-tester** [comment]
Build 944 outcome was SUCCESS using a merge of 512dc890a84bda1cd83e0242950e8fcec3bed299 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/944
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/944

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
