### PR TITLE
WELD-1873 Backport first part of WELD-1871 

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of fcb2671c22b7d8cee0c06103038a8b34161b92ac on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 780 is now running using a merge of fcb2671c22b7d8cee0c06103038a8b34161b92ac on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/780

**Comment by weld-tester** [comment]
Build 780 outcome was SUCCESS using a merge of fcb2671c22b7d8cee0c06103038a8b34161b92ac on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/780
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/780

**Comment by weld-tester** [comment]
Build 780 outcome was SUCCESS using a merge of fcb2671c22b7d8cee0c06103038a8b34161b92ac on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/780
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/780

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
