### PR TITLE
QualifierInstance - improve failure description

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by caarlos0** [comment]
Nice!

Any tips on how I can add this to an existing wildfly distrubution?

**Comment by manovotn** [comment]
@caarlos0 It is about replacing jars only.
Under Wildfly folder go to `modules/system/layers/base/org/jboss/weld`. There you will find all jars with Weld. Then:
* Build Weld with the PR
* Replace the affected jar (`core` I believe)
* If the newly created jar has a different name, reflect this name under `module.xml`

That should do the trick :)

**Comment by mkouba** [comment]
For WildFly 10 I'd rather recommend to use the update script, i.e.:
````
git clone git@github.com:weld/core.git
cd core
mvn clean install -DskipTests
export JBOSS_HOME="/path/to/wildfly10"
mvn clean package -f jboss-as/pom.xml -Pupdate-jboss-as
````
@caarlos0 I know your're trying to migrate to WildFly 9. But you could go with WildFly 10 for the testing purpose.

**Comment by caarlos0** [comment]
@mkouba my app is java 7, will not work on wildfly 10 :/

**Comment by caarlos0** [comment]
@manovotn yeah, seems like that will work, will try that! Thanks!

**Comment by mkouba** [comment]
> @mkouba my app is java 7, will not work on wildfly 10 :/
Why not? You should be able to run an app compiled with java 7 on java 8.

**Comment by caarlos0** [comment]
@mkouba real big app, lot's of "weird" and old deps, I doubt it will work... I'll try to update wildfly's 9 weld first...

**Comment by mkouba** [comment]
@caarlos0 Sure, no problem. Let us know.

**Comment by caarlos0** [comment]
@mkouba @manovotn Thanks for your help, I backported this fix to weld 2.2 [#1359] and found out the problem!

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
