### PR TITLE
WELD-1884 Add extra check for anonymous classes

### PR DESCRIPTION
**Pull request by mkouba**
- revisit the method name and test case
- http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8034044

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of f99754d4d09dcfff9de107da3a978d720c220ab8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 543 is now running using a merge of f99754d4d09dcfff9de107da3a978d720c220ab8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/543

**Comment by weld-tester** [comment]
Build 543 outcome was SUCCESS using a merge of f99754d4d09dcfff9de107da3a978d720c220ab8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/543
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/543

**Comment by weld-tester** [comment]
Build 543 outcome was SUCCESS using a merge of f99754d4d09dcfff9de107da3a978d720c220ab8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/543
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/543

**Comment by weld-tester** [comment]
Build 543 outcome was SUCCESS using a merge of f99754d4d09dcfff9de107da3a978d720c220ab8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/543
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/543

**Comment by weld-tester** [comment]
Build 543 outcome was SUCCESS using a merge of f99754d4d09dcfff9de107da3a978d720c220ab8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/543
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/543

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
