### PR TITLE
WELD-1974 Export org.jboss.weld.xml

### PR DESCRIPTION
**Pull request by hwellmann**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7d574eb63d80261d3eeb8c6a80739bb9e80c4ece on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 871 is now running using a merge of 7d574eb63d80261d3eeb8c6a80739bb9e80c4ece on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/871

**Comment by weld-tester** [comment]
Build 871 outcome was SUCCESS using a merge of 7d574eb63d80261d3eeb8c6a80739bb9e80c4ece on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/871
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/871

**Comment by weld-tester** [comment]
Build 871 outcome was SUCCESS using a merge of 7d574eb63d80261d3eeb8c6a80739bb9e80c4ece on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/871
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/871

**Comment by weld-tester** [comment]
Build 871 outcome was SUCCESS using a merge of 7d574eb63d80261d3eeb8c6a80739bb9e80c4ece on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/871
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/871

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
