### PR TITLE
Update TCK version.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by tremes** [comment]
We need to update WF container with CDI 2.0-EDR2 API to pass

**Comment by tremes** [comment]
Once this is merged then reenable TCK SE testing in CI please.

**Comment by mkouba** [comment]
retest this please

**Comment by mkouba** [comment]
retest this please

**Comment by mkouba** [comment]
Please rebase again - this commit should fix the test, thanks ;-): https://github.com/weld/core/commit/aedd9cbde18a9d699ce8f0025bdf1c902efa898f

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
