### PR TITLE
Add a test for Issue 1827

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by jharting** [comment]
ok to test

**Comment by weld-tester** [comment]
Triggering build using a merge of ab6ba82359791a6ec8cb544285f1ccc9e6ee6ba8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 390 outcome was FAILURE using a merge of ab6ba82359791a6ec8cb544285f1ccc9e6ee6ba8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/390
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/390

**Comment by weld-tester** [comment]
Build 390 outcome was FAILURE using a merge of ab6ba82359791a6ec8cb544285f1ccc9e6ee6ba8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/390
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/390

**Comment by weld-tester** [comment]
Build 390 outcome was FAILURE using a merge of ab6ba82359791a6ec8cb544285f1ccc9e6ee6ba8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/390
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/390

**Comment by weld-tester** [comment]
Build 390 outcome was FAILURE using a merge of ab6ba82359791a6ec8cb544285f1ccc9e6ee6ba8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/390
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/390

**Comment by weld-tester** [comment]
Build 390 outcome was FAILURE using a merge of ab6ba82359791a6ec8cb544285f1ccc9e6ee6ba8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/390
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/390

**Comment by jharting** [comment]
Testcase merged (with minor changes). Thanks!

**Pull request closed without merging**
