### PR TITLE
WELD-1931 Improve the performance of context activation

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of a1c50bb0b1ecac0f93a1cdf41001803e2a24269f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 755 is now running using a merge of a1c50bb0b1ecac0f93a1cdf41001803e2a24269f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/755

**Comment by weld-tester** [comment]
Build 755 outcome was FAILURE using a merge of a1c50bb0b1ecac0f93a1cdf41001803e2a24269f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/755
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/755

**Comment by weld-tester** [comment]
Build 755 outcome was FAILURE using a merge of a1c50bb0b1ecac0f93a1cdf41001803e2a24269f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/755
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/755

**Comment by weld-tester** [comment]
Triggering build using a merge of a45c30658fce44b315a5eeb078a8aeb239aec393 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 756 is now running using a merge of a45c30658fce44b315a5eeb078a8aeb239aec393 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/756

**Comment by weld-tester** [comment]
Build 756 outcome was SUCCESS using a merge of a45c30658fce44b315a5eeb078a8aeb239aec393 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/756
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/756

**Comment by weld-tester** [comment]
Build 756 outcome was SUCCESS using a merge of a45c30658fce44b315a5eeb078a8aeb239aec393 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/756
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/756

**Comment by weld-tester** [comment]
Triggering build using a merge of 211b22495ef6b6dde4f1486d4d0f591a55f0c2cc on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 757 is now running using a merge of 211b22495ef6b6dde4f1486d4d0f591a55f0c2cc on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/757

**Comment by weld-tester** [comment]
Build 757 outcome was FAILURE using a merge of 211b22495ef6b6dde4f1486d4d0f591a55f0c2cc on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/757
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/757

**Comment by weld-tester** [comment]
Triggering build using a merge of 7e58ffdd62af1daab9ceb1c681a48f4704ef09e0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 758 is now running using a merge of 7e58ffdd62af1daab9ceb1c681a48f4704ef09e0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/758

**Comment by weld-tester** [comment]
Build 758 outcome was SUCCESS using a merge of 7e58ffdd62af1daab9ceb1c681a48f4704ef09e0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/758
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/758

**Comment by weld-tester** [comment]
Build 758 outcome was SUCCESS using a merge of 7e58ffdd62af1daab9ceb1c681a48f4704ef09e0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/758
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/758

**Comment by weld-tester** [comment]
Build 758 outcome was SUCCESS using a merge of 7e58ffdd62af1daab9ceb1c681a48f4704ef09e0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/758
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/758

**Comment by weld-tester** [comment]
Build 758 outcome was SUCCESS using a merge of 7e58ffdd62af1daab9ceb1c681a48f4704ef09e0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/758
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/758

**Comment by weld-tester** [comment]
Build 758 outcome was SUCCESS using a merge of 7e58ffdd62af1daab9ceb1c681a48f4704ef09e0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/758
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/758

**Comment by weld-tester** [comment]
Triggering build using a merge of 86f4173b22e8fbd8864004fa6de03f91f231b72f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 767 is now running using a merge of 86f4173b22e8fbd8864004fa6de03f91f231b72f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/767

**Comment by weld-tester** [comment]
Build 767 outcome was FAILURE using a merge of 86f4173b22e8fbd8864004fa6de03f91f231b72f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/767
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/767

**Comment by weld-tester** [comment]
Triggering build using a merge of ee0f188773f1e37c1520618b9d402541c436e4c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 768 is now running using a merge of ee0f188773f1e37c1520618b9d402541c436e4c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/768

**Comment by weld-tester** [comment]
Build 768 outcome was FAILURE using a merge of ee0f188773f1e37c1520618b9d402541c436e4c5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/768
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/768

**Comment by weld-tester** [comment]
Triggering build using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 769 is now running using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/769

**Comment by weld-tester** [comment]
Build 769 outcome was SUCCESS using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/769
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/769

**Comment by weld-tester** [comment]
Build 769 outcome was SUCCESS using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/769
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/769

**Comment by weld-tester** [comment]
Build 769 outcome was SUCCESS using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/769
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/769

**Comment by weld-tester** [comment]
Build 769 outcome was SUCCESS using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/769
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/769

**Comment by weld-tester** [comment]
Build 769 outcome was SUCCESS using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/769
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/769

**Comment by weld-tester** [comment]
Build 769 outcome was SUCCESS using a merge of afafdc605684585d25db031948bea33f9907d9d4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/769
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/769

**Comment by weld-tester** [comment]
Triggering build using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 802 is now running using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by weld-tester** [comment]
Build 802 outcome was SUCCESS using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by weld-tester** [comment]
Build 802 outcome was SUCCESS using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by weld-tester** [comment]
Build 802 outcome was SUCCESS using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by weld-tester** [comment]
Build 802 outcome was SUCCESS using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by jharting** [comment]
Looks good. Please also provide a separate PR for 2.3

**Comment by weld-tester** [comment]
Build 802 outcome was SUCCESS using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by weld-tester** [comment]
Build 802 outcome was SUCCESS using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by weld-tester** [comment]
Build 802 outcome was SUCCESS using a merge of ac77faac90e33900658b43dcf6d41ed26f5694fb on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/802
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/802

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
