### PR TITLE
WELD-2600 Fixing issue about spec-descriptor-property-replacement and beans.xml

### PR DESCRIPTION
**Pull request by rhuan080**
Fixing issue about spec-descriptor-property-replacement and beans.xml

### CODE REVIEW

**Comment by manovotn** [comment]
@rhuan080 I suppose this needs some approval on the respective JBEAP JIRA before we want to merge it, right?

**Comment by rhuan080** [comment]
@manovotn I think too.

**Comment by manovotn** [comment]
@rhuan080 @soul2zimate should this one be merged now?

**Comment by soul2zimate** [comment]
I don't know the functional change here. If it's approved, I believe we can merge this one and https://github.com/weld/core/pull/1939 as well. Please update the fixed version in WELD-2600, I will take care of the JBEAP issue links.

**Comment by manovotn** [comment]
WELD-2600 already had the fix version.

**Pull request merged**
