### PR TITLE
WELD-1795 BeanBuilder - infer BeanBuilder type from producers

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 510 outcome was FAILURE using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/510
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/510

**Comment by weld-tester** [comment]
Build 510 outcome was FAILURE using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/510
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/510

**Comment by weld-tester** [comment]
Build 510 outcome was FAILURE using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/510
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/510

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 510 outcome was FAILURE using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/510
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/510

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 513 is now running using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/513

**Comment by weld-tester** [comment]
Build 510 outcome was FAILURE using a merge of 263b157205c8ca59d81110cca802bd8deeda6a00 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/510
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/510

**Pull request closed without merging**
