### PR TITLE
Adds directory support for Jandex discovery.

### PR DESCRIPTION
**Pull request by ljnelson**
This pull request makes a small tweak to `JandexIndexBeanArchiveHandler.java` such that directories, not just `.jar` files, are also handled.

Signed-off-by: Laird Nelson <ljnelson@gmail.com>

### CODE REVIEW

**Comment by manovotn** [comment]
Ok to test

**Comment by manovotn** [comment]
@mkouba can you recall any specific reason(s) why we decidedly avoided supporting directories?

@ljnelson may I know more about how the deployment needing this looks like?

**Comment by mkouba** [comment]
@manovotn I have no idea ;-).

**Comment by manovotn** [comment]
> @manovotn I have no idea ;-).

Well, that makes two of us  :-D

**Comment by ljnelson** [comment]
> @ljnelson may I know more about how the deployment needing this looks like?

Honestly, I just noticed it as I was reading to understand the discovery flow.  It seemed like an easy fix.

**Comment by manovotn** [comment]
Not sure we want to fix what's not broken.

**Comment by ljnelson** [comment]
Uh, OK, I'll just leave this here then!

**Comment by manovotn** [comment]
I'll close this for now as we have no real use case for it at the moment.

**Pull request closed without merging**
