### PR TITLE
WELD-1874 Make it possible to pass BeanManager to Weld listeners via con...

### PR DESCRIPTION
**Pull request by jharting**
...structor

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 584 is now running using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/584

**Comment by weld-tester** [comment]
Build 584 outcome was FAILURE using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/584
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/584

**Comment by weld-tester** [comment]
Build 584 outcome was FAILURE using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/584
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/584

**Comment by weld-tester** [comment]
Build 584 outcome was FAILURE using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/584
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/584

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 590 is now running using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/590

**Comment by weld-tester** [comment]
Build 590 outcome was SUCCESS using a merge of 7302a4be07f9f8b7be42d041e73f38ab06a31358 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/590
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/590

**Pull request closed without merging**
