### PR TITLE
Probe menu - add quick links, events dropdown (observers + fired events)

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of bfb6878510c01706672b13ee81c44b0287da9b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 527 is now running using a merge of bfb6878510c01706672b13ee81c44b0287da9b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/527

**Comment by weld-tester** [comment]
Build 527 outcome was SUCCESS using a merge of bfb6878510c01706672b13ee81c44b0287da9b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/527
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/527

**Comment by weld-tester** [comment]
Build 527 outcome was SUCCESS using a merge of bfb6878510c01706672b13ee81c44b0287da9b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/527
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/527

**Comment by jharting** [comment]
This is very nice

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
