### PR TITLE
WELD-1907 Reset initialized flag during lazy conv. context activation

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 9965c4d79175c9f6969599db476bd8150b7286d0 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 603 outcome was FAILURE using a merge of 9965c4d79175c9f6969599db476bd8150b7286d0 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/603
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/603

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 9965c4d79175c9f6969599db476bd8150b7286d0 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 606 is now running using a merge of 9965c4d79175c9f6969599db476bd8150b7286d0 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/606

**Comment by weld-tester** [comment]
Build 606 outcome was SUCCESS using a merge of 9965c4d79175c9f6969599db476bd8150b7286d0 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/606
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/606

**Comment by weld-tester** [comment]
Build 606 outcome was SUCCESS using a merge of 9965c4d79175c9f6969599db476bd8150b7286d0 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/606
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/606

**Comment by weld-tester** [comment]
Build 606 outcome was SUCCESS using a merge of 9965c4d79175c9f6969599db476bd8150b7286d0 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/606
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/606

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
