### PR TITLE
Probe: integration test refactoring+fixes

### PR DESCRIPTION
**Pull request by rsmeral**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e97346334aaebbe2d3ffb8109789d0c270401b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 553 is now running using a merge of e97346334aaebbe2d3ffb8109789d0c270401b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/553

**Comment by weld-tester** [comment]
Build 553 outcome was FAILURE using a merge of e97346334aaebbe2d3ffb8109789d0c270401b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/553
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/553

**Comment by weld-tester** [comment]
Build 553 outcome was FAILURE using a merge of e97346334aaebbe2d3ffb8109789d0c270401b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/553
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/553

**Comment by weld-tester** [comment]
Build 553 outcome was FAILURE using a merge of e97346334aaebbe2d3ffb8109789d0c270401b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/553
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/553

**Comment by weld-tester** [comment]
Build 553 outcome was FAILURE using a merge of e97346334aaebbe2d3ffb8109789d0c270401b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/553
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/553

**Comment by weld-tester** [comment]
Build 553 outcome was FAILURE using a merge of e97346334aaebbe2d3ffb8109789d0c270401b03 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/553
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/553

**Comment by jharting** [comment]
There are checkstyle failures.

**Comment by rsmeral** [comment]
Checkstyle errors fixed.

**Comment by weld-tester** [comment]
Triggering build using a merge of d439da3d2c3e332d33ed8f064bddf3a835787923 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 564 is now running using a merge of d439da3d2c3e332d33ed8f064bddf3a835787923 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/564

**Comment by weld-tester** [comment]
Build 564 outcome was SUCCESS using a merge of d439da3d2c3e332d33ed8f064bddf3a835787923 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/564
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/564

**Comment by weld-tester** [comment]
Build 564 outcome was SUCCESS using a merge of d439da3d2c3e332d33ed8f064bddf3a835787923 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/564
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/564

**Comment by weld-tester** [comment]
Build 564 outcome was SUCCESS using a merge of d439da3d2c3e332d33ed8f064bddf3a835787923 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/564
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/564

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
