### PR TITLE
WELD-1894 Disposer method invoked twice

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 572 is now running using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/572

**Comment by weld-tester** [comment]
Build 572 outcome was SUCCESS using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/572
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/572

**Comment by weld-tester** [comment]
Build 572 outcome was SUCCESS using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/572
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/572

**Comment by weld-tester** [comment]
Build 572 outcome was SUCCESS using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/572
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/572

**Comment by weld-tester** [comment]
Build 572 outcome was SUCCESS using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/572
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/572

**Comment by weld-tester** [comment]
Build 572 outcome was SUCCESS using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/572
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/572

**Comment by weld-tester** [comment]
Build 572 outcome was SUCCESS using a merge of 854c78a8806b5aeb482d8670fca98456862240b4 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/572
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/572

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
