### PR TITLE
WELD-1995 Initialize conversation id generator and map lazily

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 925 is now running using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by weld-tester** [comment]
Build 925 outcome was SUCCESS using a merge of d6d70e3e6c6e4c3087b919669552300bafb693dd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/925
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/925

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
