### PR TITLE
Upgrade Weld API to 3.0.SP1.

### PR DESCRIPTION
**Pull request by manovotn**
Blocks https://github.com/weld/core/pull/1718, https://github.com/weld/core/pull/1713, https://github.com/weld/core/pull/1685.

### CODE REVIEW

**Comment by manovotn** [comment]
Just realized the tests won't pass until we actually upgrade WFLY for Weld 3 on PR executors to include dependencies on Weld API (or make that one transient) as described in this https://github.com/weld/core/pull/1713#issuecomment-318020156

Will look into it tommorow.

**Comment by mkouba** [comment]
@manovotn I think we should add `export="true"` to `org.jboss.weld.api` and `org.jboss.weld.spi` dependencies in the core `module.xml`.

**Comment by manovotn** [comment]
retest this please

**Comment by manovotn** [comment]
The PR should be OK; note that osprey machine will fail unless WFLY gets upgraded there as well.

**Pull request merged**
