### PR TITLE
WELD-1933 Add profile to activate weld-logging-tools annotation proce…

### PR DESCRIPTION
**Pull request by mkouba**
…ssor

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 0d8c8b4c6b7889a483e0488fb47ac2d2525c700f on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 753 is now running using a merge of 0d8c8b4c6b7889a483e0488fb47ac2d2525c700f on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/753

**Comment by weld-tester** [comment]
Build 753 outcome was SUCCESS using a merge of 0d8c8b4c6b7889a483e0488fb47ac2d2525c700f on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/753
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/753

**Comment by weld-tester** [comment]
Build 753 outcome was SUCCESS using a merge of 0d8c8b4c6b7889a483e0488fb47ac2d2525c700f on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/753
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/753

**Comment by weld-tester** [comment]
Build 753 outcome was SUCCESS using a merge of 0d8c8b4c6b7889a483e0488fb47ac2d2525c700f on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/753
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/753

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
