### PR TITLE
[2.2] WELD-1832 Unify additional BDA suffix (follow the WildFly pattern)

### PR DESCRIPTION
**Pull request by mkouba**
The same modification is part of the https://github.com/weld/core/pull/825 [3.0]

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 59d8206914c60a4442239ab6b040f2b51b1e50fe on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 435 is now running using a merge of 59d8206914c60a4442239ab6b040f2b51b1e50fe on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/435

**Comment by weld-tester** [comment]
Build 435 outcome was SUCCESS using a merge of 59d8206914c60a4442239ab6b040f2b51b1e50fe on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/435
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/435

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
