### PR TITLE
Probe - minor fixes

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of eb9f4b851bd27b822b2674d5a3da5b5e61517227 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 460 is now running using a merge of eb9f4b851bd27b822b2674d5a3da5b5e61517227 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/460

**Comment by weld-tester** [comment]
Build 460 outcome was SUCCESS using a merge of eb9f4b851bd27b822b2674d5a3da5b5e61517227 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/460
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/460

**Comment by jharting** [comment]
Merged, thanks!

**Pull request merged**
