### PR TITLE
WELD-1915 Always register a shutdown hook

### PR DESCRIPTION
**Pull request by mkouba**
I don't know any reliable way of testing shutdown hooks. Therefore, I only tested this manually.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 1644e58a186866f318e4157348f37a927f78e08a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 704 outcome was FAILURE using a merge of 1644e58a186866f318e4157348f37a927f78e08a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/704
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/704

**Comment by weld-tester** [comment]
Build 704 outcome was FAILURE using a merge of 1644e58a186866f318e4157348f37a927f78e08a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/704
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/704

**Comment by weld-tester** [comment]
Triggering build using a merge of 4a815d0a098f9304486e4c8240b94671c34cbf35 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 706 is now running using a merge of 4a815d0a098f9304486e4c8240b94671c34cbf35 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/706

**Comment by weld-tester** [comment]
Build 706 outcome was FAILURE using a merge of 4a815d0a098f9304486e4c8240b94671c34cbf35 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/706
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/706

**Comment by weld-tester** [comment]
Build 706 outcome was FAILURE using a merge of 4a815d0a098f9304486e4c8240b94671c34cbf35 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/706
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/706

**Comment by mkouba** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 4a815d0a098f9304486e4c8240b94671c34cbf35 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 708 is now running using a merge of 4a815d0a098f9304486e4c8240b94671c34cbf35 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/708

**Comment by weld-tester** [comment]
Build 708 outcome was SUCCESS using a merge of 4a815d0a098f9304486e4c8240b94671c34cbf35 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/708
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/708

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
