### PR TITLE
WELD-2254 fix

### PR DESCRIPTION
**Pull request by ljnelson**
Hello; this is my first pull request to this project.  In general I am a `git` rookie.  I am happy to follow any instructions to get this pull request merged appropriately.

This pull request aims to fix [WELD-2254](https://issues.jboss.org/browse/WELD-2254).

### CODE REVIEW

**Comment by mkouba** [comment]
AFAIK zip archives are not required to contain entries for directories - in this case the fix wouldn't work. Also we don't use `assert` keyword in weld codebase.

I've tried to bring a more robust solution here:
https://github.com/mkouba/core/commit/f03f6dafdf321ef97cea2fdd79e3b6b0ed069cdb

@ljnelson Your reproducer works fine with this fix. Could you take a look at this commit and verify it makes sense? Thanks!

**Comment by ljnelson** [comment]
That looks fine to me.  Whatever works!

**Comment by mkouba** [comment]
@ljnelson Ok, I will create a new PR and it would be great if you could test it before we resolve the issue. Thanks!

**Comment by mkouba** [comment]
Closing in favor of https://github.com/weld/core/pull/1505.

@ljnelson Please test the new PR if possible. Thanks!

**Pull request closed without merging**
