### PR TITLE
WELD-1967 Revisit weld-servlet integration tests

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 876 is now running using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by weld-tester** [comment]
Build 876 outcome was SUCCESS using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by mkouba** [comment]
This commit should be merged into 2.3 branch as well.

**Comment by weld-tester** [comment]
Build 876 outcome was SUCCESS using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by weld-tester** [comment]
Build 876 outcome was SUCCESS using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by weld-tester** [comment]
Build 876 outcome was SUCCESS using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by weld-tester** [comment]
Build 876 outcome was SUCCESS using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by weld-tester** [comment]
Build 876 outcome was SUCCESS using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by weld-tester** [comment]
Build 876 outcome was SUCCESS using a merge of 7b605ce3d6749b9393b339222ac85da3ca731262 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/876
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/876

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
