### PR TITLE
Bump up TCK version.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 39f42ea916e30b2bfca9d22768db0f276e4f4a47 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 893 is now running using a merge of 39f42ea916e30b2bfca9d22768db0f276e4f4a47 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/893

**Comment by weld-tester** [comment]
Build 893 outcome was SUCCESS using a merge of 39f42ea916e30b2bfca9d22768db0f276e4f4a47 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/893
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/893

**Comment by weld-tester** [comment]
Triggering build using a merge of 2938076deec77577c5272b6d73e263709e0e2af9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 894 is now running using a merge of 2938076deec77577c5272b6d73e263709e0e2af9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/894

**Comment by weld-tester** [comment]
Build 894 outcome was SUCCESS using a merge of 2938076deec77577c5272b6d73e263709e0e2af9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/894
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/894

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
