### PR TITLE
WELD-1917 AbstractCDI - cache Instance by default

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 069cefcc4175daaa04fe6f9ea9c9dc200fc20bec on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 692 is now running using a merge of 069cefcc4175daaa04fe6f9ea9c9dc200fc20bec on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/692

**Comment by weld-tester** [comment]
Build 692 outcome was SUCCESS using a merge of 069cefcc4175daaa04fe6f9ea9c9dc200fc20bec on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/692
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/692

**Comment by jharting** [comment]
Merged, thanks!

**Pull request merged**
