### PR TITLE
WELD-1798 & WELD-1923 remove the WebServiceResourceTest.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 010f3ad2642fc93f1a891dfaf4551ef44199c1b2 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 690 outcome was FAILURE using a merge of 010f3ad2642fc93f1a891dfaf4551ef44199c1b2 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/690
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/690

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 010f3ad2642fc93f1a891dfaf4551ef44199c1b2 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 695 is now running using a merge of 010f3ad2642fc93f1a891dfaf4551ef44199c1b2 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/695

**Comment by weld-tester** [comment]
Build 695 outcome was SUCCESS using a merge of 010f3ad2642fc93f1a891dfaf4551ef44199c1b2 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/695
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/695

**Comment by weld-tester** [comment]
Build 695 outcome was SUCCESS using a merge of 010f3ad2642fc93f1a891dfaf4551ef44199c1b2 on branch 1.1:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/695
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/695

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
