### PR TITLE
WELD-1829 Always use Class.forName() as a fallback (even if the TCCL is

### PR DESCRIPTION
**Pull request by mkouba**
set)

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 4e70bf539a08b80d962388299c85259053426ffe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 410 is now running using a merge of 4e70bf539a08b80d962388299c85259053426ffe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/410

**Comment by weld-tester** [comment]
Build 410 outcome was FAILURE using a merge of 4e70bf539a08b80d962388299c85259053426ffe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/410
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/410

**Comment by mkouba** [comment]
FYI the failure on jenkins CI is not related. This is the test which fails: `org.jboss.weld.tests.jsf.managedbeans.ManagedBeansWithCDITest`. I'm not sure what's happening. Maybe some intermittent failure...

**Comment by weld-tester** [comment]
Build 410 outcome was FAILURE using a merge of 4e70bf539a08b80d962388299c85259053426ffe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/410
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/410

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 4e70bf539a08b80d962388299c85259053426ffe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 413 is now running using a merge of 4e70bf539a08b80d962388299c85259053426ffe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/413

**Comment by weld-tester** [comment]
Build 413 outcome was SUCCESS using a merge of 4e70bf539a08b80d962388299c85259053426ffe on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/413
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/413

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
