### PR TITLE
WELD-1959 Jetty fixes

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of c62ac7fcd96d3bf7fc20afd33198a21d99299b97 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Triggering build using a merge of ed7a57052db002df276679487bd8f234b49c5901 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 787 is now running using a merge of ed7a57052db002df276679487bd8f234b49c5901 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/787

**Comment by weld-tester** [comment]
Build 787 outcome was SUCCESS using a merge of ed7a57052db002df276679487bd8f234b49c5901 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/787
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/787

**Comment by mkouba** [comment]
@tremes FYI this is the relevant Jetty bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=419801

**Comment by weld-tester** [comment]
Build 787 outcome was SUCCESS using a merge of ed7a57052db002df276679487bd8f234b49c5901 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/787
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/787

**Comment by weld-tester** [comment]
Build 787 outcome was SUCCESS using a merge of ed7a57052db002df276679487bd8f234b49c5901 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/787
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/787

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
