### PR TITLE
Probe - next improvements

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of d1d259edf44cf96a5db10337afca96413d2265ed on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 431 is now running using a merge of d1d259edf44cf96a5db10337afca96413d2265ed on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/431

**Comment by weld-tester** [comment]
Build 431 outcome was SUCCESS using a merge of d1d259edf44cf96a5db10337afca96413d2265ed on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/431
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/431

**Comment by weld-tester** [comment]
Triggering build using a merge of 329d77847a0efc2649cc74e348a47772824a21e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 434 is now running using a merge of 329d77847a0efc2649cc74e348a47772824a21e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/434

**Comment by weld-tester** [comment]
Build 434 outcome was SUCCESS using a merge of 329d77847a0efc2649cc74e348a47772824a21e2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/434
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/434

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
