### PR TITLE
Backport testcase for WFLY-4438.

### PR DESCRIPTION
**Pull request by manovotn**

### CODE REVIEW

**Comment by mkouba** [comment]
@manovotn It seems we will have to wait for JBoss EAP 6.4.11.

**Comment by manovotn** [comment]
True, I tested this on CR build of EAP 6.4.11.
Though I am not sure what does the CI jenkins job run against? (EAP/JBoss 7) It wouldn't make much sense to backport this unless we test against EAP.

**Comment by mkouba** [comment]
The job runs against JBoss EAP 6.4.4.

**Comment by mkouba** [comment]
retest this please

**Comment by mkouba** [comment]
Merged, thanks!

**Pull request closed without merging**
