### PR TITLE
Sync ActionSequence with the TCK one.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 3ca6847ee01fefabfe9b5494518ece26be816faf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 929 outcome was FAILURE using a merge of 3ca6847ee01fefabfe9b5494518ece26be816faf on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/929
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/929

**Comment by weld-tester** [comment]
Triggering build using a merge of d5a386445ee12eaf5f35088c8b399bcee6ab4c2f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 931 is now running using a merge of d5a386445ee12eaf5f35088c8b399bcee6ab4c2f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/931

**Comment by weld-tester** [comment]
Build 931 outcome was FAILURE using a merge of d5a386445ee12eaf5f35088c8b399bcee6ab4c2f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/931
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/931

**Comment by weld-tester** [comment]
Triggering build using a merge of b8fb8cc0c4f5515213577de50f257f5e63f8119a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 932 is now running using a merge of b8fb8cc0c4f5515213577de50f257f5e63f8119a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/932

**Comment by weld-tester** [comment]
Build 932 outcome was SUCCESS using a merge of b8fb8cc0c4f5515213577de50f257f5e63f8119a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/932
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/932

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
