### PR TITLE
WELD-1934 weld-servlet-core has hard dependency on jsp

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 376cc1930a53996969c3261762a57cf51d11501a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 721 is now running using a merge of 376cc1930a53996969c3261762a57cf51d11501a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/721

**Comment by weld-tester** [comment]
Build 721 outcome was FAILURE using a merge of 376cc1930a53996969c3261762a57cf51d11501a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/721
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/721

**Comment by weld-tester** [comment]
Build 721 outcome was FAILURE using a merge of 376cc1930a53996969c3261762a57cf51d11501a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/721
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/721

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of 376cc1930a53996969c3261762a57cf51d11501a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 722 is now running using a merge of 376cc1930a53996969c3261762a57cf51d11501a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/722

**Comment by weld-tester** [comment]
Build 722 outcome was SUCCESS using a merge of 376cc1930a53996969c3261762a57cf51d11501a on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/722
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/722

**Pull request merged**
