### PR TITLE
WELD-1871 Next part, WELD-1971

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 078cecd3f5e9f90cd3cad0aa1133fbdc7c1e7915 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 857 is now running using a merge of 078cecd3f5e9f90cd3cad0aa1133fbdc7c1e7915 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/857

**Comment by weld-tester** [comment]
Build 857 outcome was SUCCESS using a merge of 078cecd3f5e9f90cd3cad0aa1133fbdc7c1e7915 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/857
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/857

**Comment by weld-tester** [comment]
Build 857 outcome was SUCCESS using a merge of 078cecd3f5e9f90cd3cad0aa1133fbdc7c1e7915 on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/857
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/857

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
