### PR TITLE
Allow usage of InterceptionFactory  on interfaces

### PR DESCRIPTION
**Pull request by kalgon**
In case you change your mind about [CDI-686](https://issues.jboss.org/browse/CDI-686), I modified `InterceptedProxyFactory` to proxy methods even if the proxied bean type is an interface.

### CODE REVIEW

**Comment by manovotn** [comment]
ok to test

**Comment by manovotn** [comment]
Hi @kalgon 

I was just fiddling with something similar myself (though my approach is different).
Thanks for this PR, I will look into it tomorrow and leave a comment here.

**Comment by kalgon** [comment]
@manovotn, glad to hear you are working on it too! I bet your approach will be better than mine (it's the first time I dig into weld code and I did the bare minimum to make it work).

**Comment by manovotn** [comment]
Just for reference, the PR I was referring to is https://github.com/weld/core/pull/1873

**Comment by manovotn** [comment]
Closing in favor of #1873

**Pull request closed without merging**
