### PR TITLE
TCK runner - add dependenciesToScan

### PR DESCRIPTION
**Pull request by mkouba**
- https://issues.apache.org/jira/browse/SUREFIRE-569

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 9c70acbec8d407dd0d3a6f62963ac67b48ad09bd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 908 is now running using a merge of 9c70acbec8d407dd0d3a6f62963ac67b48ad09bd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/908

**Comment by weld-tester** [comment]
Build 908 outcome was SUCCESS using a merge of 9c70acbec8d407dd0d3a6f62963ac67b48ad09bd on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/908
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/908

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
