### PR TITLE
Probe tests - add WF-9 profile.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of ad04464dd41e1f6e3957f3340dae71c8f876a83f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 614 is now running using a merge of ad04464dd41e1f6e3957f3340dae71c8f876a83f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/614

**Comment by weld-tester** [comment]
Build 614 outcome was FAILURE using a merge of ad04464dd41e1f6e3957f3340dae71c8f876a83f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/614
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/614

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of ad04464dd41e1f6e3957f3340dae71c8f876a83f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 616 is now running using a merge of ad04464dd41e1f6e3957f3340dae71c8f876a83f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/616

**Comment by weld-tester** [comment]
Build 616 outcome was SUCCESS using a merge of ad04464dd41e1f6e3957f3340dae71c8f876a83f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/616
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/616

**Comment by weld-tester** [comment]
Build 616 outcome was SUCCESS using a merge of ad04464dd41e1f6e3957f3340dae71c8f876a83f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/616
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/616

**Comment by weld-tester** [comment]
Triggering build using a merge of 992cf596610f987d16cc1b5d00dd33a671e034c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 620 is now running using a merge of 992cf596610f987d16cc1b5d00dd33a671e034c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/620

**Comment by weld-tester** [comment]
Build 620 outcome was FAILURE using a merge of 992cf596610f987d16cc1b5d00dd33a671e034c2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/620
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/620

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
