### PR TITLE
Testing CI

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e958ef34291b6200c5187a581afd06002b4a6efb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 624 is now running using a merge of e958ef34291b6200c5187a581afd06002b4a6efb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/624

**Comment by weld-tester** [comment]
Build 624 outcome was FAILURE using a merge of e958ef34291b6200c5187a581afd06002b4a6efb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/624
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/624

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of e958ef34291b6200c5187a581afd06002b4a6efb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 637 outcome was FAILURE using a merge of e958ef34291b6200c5187a581afd06002b4a6efb on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/637
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/637

**Comment by weld-tester** [comment]
Triggering build using a merge of ff8983ea6c6de14922eca04fd8a30286cc7183d6 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 643 is now running using a merge of ff8983ea6c6de14922eca04fd8a30286cc7183d6 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/643

**Comment by weld-tester** [comment]
Build 643 outcome was SUCCESS using a merge of ff8983ea6c6de14922eca04fd8a30286cc7183d6 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/643
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/643

**Comment by weld-tester** [comment]
Build 648 outcome was SUCCESS using a merge of ff8983ea6c6de14922eca04fd8a30286cc7183d6 on branch 2.2:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/648
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/648

**Pull request closed without merging**
