### PR TITLE
Update inject and cdi TCK versions; Pending Ballots

### PR DESCRIPTION
**Pull request by starksm64**
Signed-off-by: Scott M Stark <starksm64@gmail.com>

### CODE REVIEW

**Comment by manovotn** [comment]
whitelist

**Comment by manovotn** [comment]
@starksm64 the build won't run by default with staging profiles (which is probably why travis failed?). Neither I think it should - is this for some temporary testing/verification you are doing?
If possible I think we should avoid having versions in master that are just staged as that can prevent reproducibility of builds.

**Comment by starksm64** [comment]
@manovotn This updates the TCK versions to those that are going to be released as soon as the specification ballots pass. The staging profile is to allow testing of the Jakarta staged versions that are undergoing ballot. I updated the title to say ...Pending Ballots. I'll remove that once the ballots conclude and the TCKs are released to maven central.

**Comment by manovotn** [comment]
The PR wasn't compileable.
Also, it now needs rebase because at least one of those deps is already released and was updated.

**Comment by manovotn** [comment]
Closing PR for inactivity. Besides, most of the deps mentioned here should be updated at this point.

**Pull request closed without merging**
