### PR TITLE
WELD-1885 testcase

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 986a08fb162bb8e38b31d5a1bdcffd93ed2d3ff1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Can one of the admins verify this patch?

**Comment by weld-tester** [comment]
Build 546 is now running using a merge of 986a08fb162bb8e38b31d5a1bdcffd93ed2d3ff1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/546

**Comment by weld-tester** [comment]
Build 546 outcome was SUCCESS using a merge of 986a08fb162bb8e38b31d5a1bdcffd93ed2d3ff1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/546
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/546

**Comment by weld-tester** [comment]
Triggering build using a merge of 28a19257c9de82f37af3aa1889143e48944f9d40 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 550 is now running using a merge of 28a19257c9de82f37af3aa1889143e48944f9d40 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/550

**Comment by weld-tester** [comment]
Build 550 outcome was SUCCESS using a merge of 28a19257c9de82f37af3aa1889143e48944f9d40 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/550
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/550

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
