### PR TITLE
WELD-1987 Fix format in some log messages

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 58ba3732167ecbd5c7e1d66fcc2c8c29f4d3cbc5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 911 is now running using a merge of 58ba3732167ecbd5c7e1d66fcc2c8c29f4d3cbc5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/911

**Comment by weld-tester** [comment]
Build 911 outcome was SUCCESS using a merge of 58ba3732167ecbd5c7e1d66fcc2c8c29f4d3cbc5 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/911
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/911

**Comment by mkouba** [comment]
Merged.

**Pull request closed without merging**
