### PR TITLE
WELD-1900,  WELD-1902 Probe - clippy support, group invocations within the same request

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 90ad81b7cf5d33ffce22fffda68199f732f9fff0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 630 is now running using a merge of 90ad81b7cf5d33ffce22fffda68199f732f9fff0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/630

**Comment by weld-tester** [comment]
Build 630 outcome was FAILURE using a merge of 90ad81b7cf5d33ffce22fffda68199f732f9fff0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/630
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/630

**Comment by weld-tester** [comment]
Triggering build using a merge of a4f1751de8cacc9e98c5d9726935db837cd94a52 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 636 is now running using a merge of a4f1751de8cacc9e98c5d9726935db837cd94a52 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/636

**Comment by weld-tester** [comment]
Build 636 outcome was FAILURE using a merge of a4f1751de8cacc9e98c5d9726935db837cd94a52 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/636
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/636

**Comment by jharting** [comment]
retest this please

**Comment by weld-tester** [comment]
Triggering build using a merge of a4f1751de8cacc9e98c5d9726935db837cd94a52 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 640 is now running using a merge of a4f1751de8cacc9e98c5d9726935db837cd94a52 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/640

**Comment by weld-tester** [comment]
Build 640 outcome was FAILURE using a merge of a4f1751de8cacc9e98c5d9726935db837cd94a52 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/640
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/640

**Comment by mkouba** [comment]
`ProbeInvocationsTest` needs to be fixed.

**Comment by weld-tester** [comment]
Triggering build using a merge of 8b9a10057043b4bdedcb43f38a62ac2350389530 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 645 is now running using a merge of 8b9a10057043b4bdedcb43f38a62ac2350389530 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/645

**Comment by weld-tester** [comment]
Build 645 outcome was SUCCESS using a merge of 8b9a10057043b4bdedcb43f38a62ac2350389530 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/645
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/645

**Comment by weld-tester** [comment]
Triggering build using a merge of 1762a426012d4ec454bd91ef7b9ef4c50cac7c79 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 650 is now running using a merge of 1762a426012d4ec454bd91ef7b9ef4c50cac7c79 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/650

**Comment by weld-tester** [comment]
Triggering build using a merge of 31e931c79828daef0eb5d406cb24079a3bd9e25a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 651 is now running using a merge of 31e931c79828daef0eb5d406cb24079a3bd9e25a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/651

**Comment by weld-tester** [comment]
Build 651 outcome was SUCCESS using a merge of 31e931c79828daef0eb5d406cb24079a3bd9e25a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/651
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/651

**Comment by weld-tester** [comment]
Triggering build using a merge of 396d7540a25675b8aee1c62f95c32f093eed1b74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 652 is now running using a merge of 396d7540a25675b8aee1c62f95c32f093eed1b74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/652

**Comment by weld-tester** [comment]
Build 652 outcome was SUCCESS using a merge of 396d7540a25675b8aee1c62f95c32f093eed1b74 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/652
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/652

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
