### PR TITLE
WELD-1925 Special treatment of Instance<?>

### PR DESCRIPTION
**Pull request by mkouba**
* `Instance<?>` is only treated specially in the bean detail
* dependencies - we don't leave out `InstanceImpl` entirely but add virtual dependencies to its set of dependencies
* dependents - `InstanceImpl` is omitted, virtual dependency is added

The different handling for dependencies and dependents might seem inconsistent but I believe that it makes sense.

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of b0a97789163ccd7eca13a80a6218ada174707c9f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 709 is now running using a merge of b0a97789163ccd7eca13a80a6218ada174707c9f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/709

**Comment by weld-tester** [comment]
Build 709 outcome was SUCCESS using a merge of b0a97789163ccd7eca13a80a6218ada174707c9f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/709
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/709

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
