### PR TITLE
Upgrade TCK and Arquillian versions.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of c01f7974bfcbbcc5cb6d7741dd8894b495ee9199 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 761 is now running using a merge of c01f7974bfcbbcc5cb6d7741dd8894b495ee9199 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/761

**Comment by weld-tester** [comment]
Build 761 outcome was SUCCESS using a merge of c01f7974bfcbbcc5cb6d7741dd8894b495ee9199 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/761
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/761

**Comment by mkouba** [comment]
Merged. Thanks!

**Pull request closed without merging**
