### PR TITLE
Probe - Weld configutation improvements

### PR DESCRIPTION
**Pull request by mkouba**
- sort config keys
- show brief description

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 874 is now running using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by weld-tester** [comment]
Build 874 outcome was SUCCESS using a merge of 7502b3e64911a250e899ad5b57dca2862373491f on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/874
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/874

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
