### PR TITLE
WELD-1867 Probe Contexts - add support for @ConversationScoped

### PR DESCRIPTION
**Pull request by mkouba**
- also fix Bean Archive detail - selected alternatives (stereotypes)

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of e30d7e81a05d2dd584f4fbc743e51d7f7c2e1c45 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 503 is now running using a merge of e30d7e81a05d2dd584f4fbc743e51d7f7c2e1c45 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/503

**Comment by weld-tester** [comment]
Build 503 outcome was SUCCESS using a merge of e30d7e81a05d2dd584f4fbc743e51d7f7c2e1c45 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/503
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/503

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
