### PR TITLE
WELD-1959 Update docs

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of cf965bda8f851dfd25e4cd8ec072997e4fd8b35f on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 809 is now running using a merge of cf965bda8f851dfd25e4cd8ec072997e4fd8b35f on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/809

**Comment by jharting** [comment]
Merged, thanks!

**Comment by mkouba** [comment]
https://github.com/weld/weld.github.io/pull/11#issuecomment-108906966

**Comment by weld-tester** [comment]
Build 809 outcome was SUCCESS using a merge of cf965bda8f851dfd25e4cd8ec072997e4fd8b35f on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/809
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/809

**Comment by weld-tester** [comment]
Triggering build using a merge of 8f75735f1905ff2ef5bbdb95eb1698a82bc84f8c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 816 is now running using a merge of 8f75735f1905ff2ef5bbdb95eb1698a82bc84f8c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/816

**Comment by weld-tester** [comment]
Build 816 outcome was SUCCESS using a merge of 8f75735f1905ff2ef5bbdb95eb1698a82bc84f8c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/816
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/816

**Comment by weld-tester** [comment]
Build 816 outcome was SUCCESS using a merge of 8f75735f1905ff2ef5bbdb95eb1698a82bc84f8c on branch 2.3:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/816
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/816

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
