### PR TITLE
Probe integration tests - invocations test expanded.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 569 is now running using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/569

**Comment by weld-tester** [comment]
Build 569 outcome was SUCCESS using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/569
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/569

**Comment by weld-tester** [comment]
Build 569 outcome was SUCCESS using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/569
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/569

**Comment by weld-tester** [comment]
Build 569 outcome was SUCCESS using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/569
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/569

**Comment by weld-tester** [comment]
Build 569 outcome was SUCCESS using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/569
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/569

**Comment by weld-tester** [comment]
Build 569 outcome was SUCCESS using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/569
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/569

**Comment by weld-tester** [comment]
Build 569 outcome was SUCCESS using a merge of 298322b5db2ff4681517efce91d54b54cb42b1c3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/569
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/569

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
