### PR TITLE
Probe: make Strings JSON parts public, simplify the use of JSON generator

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by weld-tester** [comment]
Triggering build using a merge of fd80966cec1752cca86a3cab916f5e7671398f25 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/

**Comment by weld-tester** [comment]
Build 514 is now running using a merge of fd80966cec1752cca86a3cab916f5e7671398f25 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/514

**Comment by weld-tester** [comment]
Build 514 outcome was SUCCESS using a merge of fd80966cec1752cca86a3cab916f5e7671398f25 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/514
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/514

**Comment by weld-tester** [comment]
Build 514 outcome was SUCCESS using a merge of fd80966cec1752cca86a3cab916f5e7671398f25 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/514
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/514

**Comment by weld-tester** [comment]
Build 514 outcome was SUCCESS using a merge of fd80966cec1752cca86a3cab916f5e7671398f25 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/Weld-2.x-pull-player-executor-osprey/514
Public: https://hudson.jboss.org/hudson/job/Weld-2.x-pull-player-executor-osprey/514

**Comment by jharting** [comment]
Merged, thanks!

**Pull request closed without merging**
