### PR TITLE
Do not include same class path entries from class path property and manifest entries

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by manovotn** [comment]
@Vampire this commit could probably be appended to https://github.com/weld/core/pull/2564?

**Comment by Vampire** [comment]
I would have rebased it after that was merged, but I can of course also incorporate it, however you like

**Comment by manovotn** [comment]
@Vampire incorporate it please, it is very much related to fixing the same class and will be easier for future tracking :)

**Comment by Vampire** [comment]
Done

**Pull request closed without merging**
